import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(file){const exports={};const code=ts.transpileModule(readFileSync(new URL('../src/lib/'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('exports',code)(exports);return exports;}
const {sessionPolicy,validateSessionPolicy,policyFromFields}=load('remote-session-policy.ts');
const {ApprovalPresentation,canApprove,remainingSeconds,pendingChats}=load('chat-authorization.ts');
const grant={id:'A',fingerprint:'synthetic',status:'pending',scopes:['files.read','exec.run'],created_at:10,expires_at:100,idle_expires_at:100};
const row={workspaceId:'one',workspaceName:'Synthetic',exclusive:true,grant};
test('single-owner and long-development defaults use seconds, not refresh schedules',()=>{assert.deepEqual(sessionPolicy(),{exclusive:true,access_token_ttl_seconds:3600,refresh_session_ttl_seconds:2592000,chat_lease_ttl_seconds:86400,chat_idle_timeout_seconds:0});assert.equal(validateSessionPolicy(sessionPolicy()),'');});
test('unit conversion and every TTL boundary are validated',()=>{assert.deepEqual(policyFromFields(true,60,30,24,0),sessionPolicy());for(const args of [[true,undefined,30,24,0],[true,1,30,24,0],[true,481,30,24,0],[true,60,91,24,0],[true,60,30,721,0],[true,60,30,1,120],[true,60,30,24,1],[true,60,30,1.5,0],[true,NaN,30,24,0],[true,Infinity,30,24,0]])assert.throws(()=>policyFromFields(...args));assert.equal(validateSessionPolicy(policyFromFields(false,5,1,1,30)),'');assert.equal(validateSessionPolicy(policyFromFields(true,480,90,720,1440)),'');});
test('approval requires explicit fingerprint confirmation and nonempty subset before expiry',()=>{assert.equal(canApprove(grant,['files.read'],true,11),true);for(const [scopes,verified,now]of [[[],true,11],[['harness.write'],true,11],[['files.read'],false,11],[['files.read'],true,100]])assert.equal(canApprove(grant,scopes,verified,now),false);assert.equal(canApprove({...grant,status:'expired'},['files.read'],true,11),false);assert.equal(remainingSeconds(grant,1000),0);});
test('100 invalidations do not reopen a dismissed approval',()=>{const p=new ApprovalPresentation();assert.equal(p.choose([row],true),row);for(let i=0;i<100;i++)assert.equal(p.choose([row],true),null);assert.equal(p.choose([row],true,true),row);});
test('background snapshot does not steal focus; explicit tray action may open it',()=>{const p=new ApprovalPresentation();assert.equal(p.choose([row],false),null);assert.equal(p.choose([row],false,true),row);});
test('snapshot resync removes old requests and presentation state',()=>{const p=new ApprovalPresentation();p.choose([row],true);assert.equal(p.choose([],true),null);assert.equal(p.choose([row],true),row);assert.deepEqual(pendingChats({revision:1,now:100,pending:[row]}),[]);assert.deepEqual(pendingChats({revision:2,now:99,pending:[row]}),[row]);});
test('global host is mounted outside a workspace and authoritative actions stay IPC-only',()=>{const root=readFileSync(new URL('../src/routes/+layout.svelte',import.meta.url),'utf8');assert.match(root,/<ChatAuthorizationHost\s*\/>/);const host=readFileSync(new URL('../src/lib/components/ChatAuthorizationHost.svelte',import.meta.url),'utf8');assert.match(host,/chat_authorization_inbox/);assert.match(host,/chat-authorization-changed/);assert.match(host,/snapshot.revision < revision/);assert.doesNotMatch(host,/refresh_token|access_token|openai\/session/);});
