import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=readFileSync(new URL('../src/lib/workspace-snapshots.ts',import.meta.url),'utf8');
const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {createWorkspaceSnapshotsController}=await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const target={id:'a'.repeat(32),display_path:'managed/test',head:'b'.repeat(40),detached:true,native_profile_id:'native-workspace'};
const snapshot={id:'c'.repeat(32),digest:'d'.repeat(64),bytes:3,entries:[]};
const plan={id:'e'.repeat(32),snapshot_id:snapshot.id,worktree_id:target.id,approval_digest:'f'.repeat(64),current_digest:'0'.repeat(64),snapshot_digest:snapshot.digest,expires_at:Date.now()/1000+100,changes:[{path:'a',action:'replace'}]};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{resolve,reject,promise}};
function setup(handler=async()=>undefined){let view;let registered=0;const calls=[];const controller=createWorkspaceSnapshotsController('source-workspace',async(command,args)=>{calls.push({command,args});const custom=await handler(command,args);if(custom!==undefined)return custom;return command==='list_managed_workspaces'?[target]:command==='snapshot_list'?[snapshot]:command==='snapshot_plan_restore'?plan:{}},next=>view=next,async()=>{registered++});return{controller,calls,get view(){return view},get registered(){return registered}};}
async function selected(s){await s.controller.refresh();await s.controller.select(target.id)}
test('mount and selection are read-only',async()=>{const s=setup();await selected(s);assert.deepEqual(s.calls.map(c=>c.command),['list_managed_workspaces','snapshot_list']);assert.equal(s.view.selected,target.id)});
test('unregistered target cannot capture or plan until explicit native registration',async()=>{const s=setup(async cmd=>cmd==='list_managed_workspaces'?[{...target,native_profile_id:null}]:undefined);await selected(s);await s.controller.act('capture');await s.controller.act('plan',snapshot.id);assert.equal(s.calls.length,1)});
test('registration cancellation submits no further changes',async()=>{const s=setup(async cmd=>cmd==='list_managed_workspaces'?[{...target,native_profile_id:null}]:cmd==='register_managed_workspace'?null:undefined);await selected(s);await s.controller.act('register');assert.equal(s.registered,0);assert.match(s.view.notice,/取消/);assert.equal(s.calls.length,2)});
test('registration refreshes navigation without auto-start or permission changes',async()=>{const s=setup(async cmd=>cmd==='list_managed_workspaces'?[{...target,native_profile_id:null}]:cmd==='register_managed_workspace'?{id:'fresh'}:undefined);await selected(s);await s.controller.act('register');assert.equal(s.registered,1);assert.equal(s.view.targets[0].native_profile_id,'fresh');assert.deepEqual(s.calls.map(c=>c.command),['list_managed_workspaces','register_managed_workspace'])});
test('restore passes only exact server plan ID and digest to native confirmation',async()=>{const s=setup();await selected(s);await s.controller.act('plan',snapshot.id);await s.controller.act('restore');assert.deepEqual(s.calls.at(-1),{command:'snapshot_restore',args:{sourceId:'source-workspace',worktreeId:target.id,planId:plan.id,approvalDigest:plan.approval_digest}});assert.equal(s.view.plan,null)});
test('expiry prevents submission',async()=>{const s=setup(async cmd=>cmd==='snapshot_plan_restore'?{...plan,expires_at:0}:undefined);await selected(s);await s.controller.act('plan',snapshot.id);await s.controller.act('restore');assert.equal(s.calls.filter(c=>c.command==='snapshot_restore').length,0)});
test('double clicks cannot create duplicate captures',async()=>{const pending=deferred();const s=setup(cmd=>cmd==='snapshot_capture'?pending.promise:Promise.resolve(undefined));await selected(s);const first=s.controller.act('capture');await Promise.resolve();await s.controller.act('capture');pending.resolve({});await first;assert.equal(s.calls.filter(c=>c.command==='snapshot_capture').length,1)});
test('late read after workspace disposal cannot publish',async()=>{const pending=deferred();const s=setup(cmd=>cmd==='snapshot_plan_restore'?pending.promise:Promise.resolve(undefined));await selected(s);const op=s.controller.act('plan',snapshot.id);s.controller.dispose();const view=s.view;pending.resolve(plan);await op;assert.equal(s.view,view);assert.equal(s.view.plan,null)});
test('uncertain restore is redacted and locked against retry',async()=>{const s=setup(async cmd=>{if(cmd==='snapshot_restore')throw Error('SECRET_CONTENT');});await selected(s);await s.controller.act('plan',snapshot.id);await s.controller.act('restore');assert.equal(s.view.uncertain,true);assert.doesNotMatch(s.view.error,/SECRET_CONTENT/);await s.controller.act('restore');await s.controller.act('capture');assert.equal(s.calls.filter(c=>c.command==='snapshot_restore').length,1);assert.equal(s.calls.filter(c=>c.command==='snapshot_capture').length,0)});
test('UI discloses platform/bounds, local confirmation, preserved authority and backup limits',()=>{const s=readFileSync(new URL('../src/lib/components/WorkspaceSnapshots.svelte',import.meta.url),'utf8');for(const term of ['Windows','256','16 MiB','单文件最多 1 MiB','本机对话框','外部编辑器','恢复日志'])assert.ok(s.includes(term));assert.doesNotMatch(s,/console\.|localStorage|sessionStorage/)});
