"""Finite supervisor readiness admission; independent full-tree review binds this module."""
import hashlib
import rc_pretag_ownership_profile as o
import rc_pretag_publication_profile as p

M = '69e749736b95b5921b4f6352838f69860c7a0a4e'
M_TREE = '0b14817a668e8d5f25b23ab3bb088fbf65ca8849'
M_PARENTS = ('f9d414b0c85348da79fee80c3b04bf5a06daf1d7', '7f210716d43bb4a7097778c087e37ecbd86c7ec2')
M_RAW = (1245, '578e9f9415c5f31ad15289e7abbe553a4a736bdf60e2e65e595e1157f01b8619')
PROFILE = 'scripts/rc_pretag_supervisor_readiness_profile.py'
CASES = 'scripts/rc_pretag_supervisor_readiness_cases.py'
DISPATCHER = 'scripts/rc_pretag_staged_bytes_profile.py'
WORKFLOW = '.github/workflows/issue88-publication-executor.yml'
CAPS = {
    '.github/workflows/issue88-publication-executor.yml': (149, 14),
    'docs/specs/issue88-supervisor-readiness/design.md': (70, 70),
    'docs/specs/issue88-supervisor-readiness/requirements.md': (40, 40),
    'docs/specs/issue88-supervisor-readiness/tasks.md': (55, 55),
    'scripts/rc_consumer_transport_supervisor_tests.py': (462, 34),
    'scripts/rc_pretag_composition_tests.py': (490, 2),
    'scripts/rc_pretag_staged_bytes_cases.py': (447, 27),
    'scripts/rc_pretag_staged_bytes_profile.py': (223, 6),
    'scripts/rc_pretag_supervisor_readiness_cases.py': (400, 400),
    'scripts/rc_pretag_supervisor_readiness_profile.py': (300, 300),
}
BASE_PINS = {
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'f76a50f14444f1b1c5959fa27097a85d87bfe8b0', '1ba5c751af0b605efc3f6f8165aa9b97f13d3c93d973493b451cc7bca2c53cff', 11488, 139),
    'scripts/rc_consumer_transport_supervisor_tests.py': ('100644', 'e45608f7ae523c25ea5d12cd4d24cbd56a3f1c12', '621c544e5c2062756346cbbd3218a8f7a65ae69bf25fff16ea6746025438e2cb', 22214, 438),
    'scripts/rc_pretag_composition_tests.py': ('100644', '5c9b6e051f2e8e34a1a84d00e4cd9465627ed670', 'a0504babffa24689fa16d29d4832778a6067783c0ee82fe477f59919a12f2a96', 36502, 490),
    'scripts/rc_pretag_staged_bytes_cases.py': ('100644', '1d342ccbbe07b138b59723dfe0a6ef78afb1bd50', 'b8557cb0721b8c36b092bcf1328f644afe892028dd29bc18ed0057854a633e87', 32100, 446),
    'scripts/rc_pretag_staged_bytes_profile.py': ('100644', 'a9e52eba5bc9e35148c113ec7cbabd9801fd6678', 'c6d247fec3ea1146cd80cd3665449c573a482e138b24664c7298288a99c283cc', 51424, 217),
}
PRIOR_PINS = {
    '.github/workflows/issue88-publication-executor.yml': (('6af82d85156eda76f2fd464a7bd72b1e78ea3e53', '451bbeffce17f243a9f3b02f7e91c03c847e92c62caa2c9d40a3062103354dac'), ('2e287f38ffc6cbcdc9da82277bce9e1c25bc7a50', '377086ca7c6edb11fbace99c35340bb4147c2102123d96cd00ef3a3e196f0979'), ('a61797b57dcba000d238dbd2c224247ec077cdbc', '28601d9ded709b55ccad36f966a106e2912d67c48ec47833b9b519e1524045dc'), ('a81e9404bae5e4a56599eb0455026c207acbdc27', 'ef64753deb51f2260812bf136ad4bca0d811bc84e61e601e80697fdef314181c'), ('f3cf8b1e3f337204f423ae200e667aaf9d34e3f8', '5fedc956307b75e7d59c3f5aeda153b6e3e64dd618700141862149c3fda37d7a'), ('d06143c505bf739dfd4336ea97c20b5850d15128', 'ceb14dd7012995f1d3400e1eb7dfc24533b564cd9a039e2592c74b153d036634'), ('c6cc466d9d2520b668508e6fbd9754f1ac1cc7ef', '850aea3f1d81c00322f8c8ca1adf84a5abddb5c75d916066394f41a521397e4e')),
    'scripts/rc_pretag_composition_tests.py': (('2bebb78514e8e7c8358e5bac4c2cbfb2d09ecd8b', 'b285be0f99bfa93aaa21179c8b97a248c3afbfa4c7b977fa3e52e22d041eb4ce'), ('56549d0a55f3162dfb7b3ed993e4ddcff18ff69f', '105f8562da48ff4557898e017ead8762f55e55357a664e1372e1443d25f217e2'), ('988c4be1175b68feecc2c38f8aee7f932e4589e2', 'ff5e95e6ff14416aa969e1c9dad9e729c96c3aa624da63af4ff93c9edc397694'), ('99483e8545add6209aee035b7460d5b56c023a82', 'f0cf5e2ff2739efd976125d893bf9cd58a5c1d0706a4b9cf95d998811b706488'), ('67e97761d6570869e64ea04276b635cd89f3ccc1', '5bf44aac60240fb6ee5d0af5afd82a8aa16ff4008ec78530cab937753e47a029'), ('f306ba3902577acc5f8d3b8c0537b1921050e062', '061036efcb39239f3251d3f212472166c2f5f2b1a2d37c3cc9ea0e75da8b4a4a'), ('959bddf9d5f32767e033418bb4823e8c7ef32a77', '132fb6b5760fbefdb0d728f8400d3ee8544c6218329483e5ec5828d2f6b81cf6'), ('6aceb93ede42cecac841e12d30bd35ae156ba8ef', '61098cd058653f1585ae35bcec620ab8a209535cf8b81b78dcbb47b62e88c10c'), ('00d8e657375a479779d7c06ef33cb847ff9f49d0', 'e8c1ac54d30a4030f9b843aeee1c1ff1a94013641f533f1e97e35603d25e8c74')),
}
DELTA_LIMIT = 1000
# BEGIN SEALED SOURCE
SOURCE_PINS = {
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'e740760c079a8a831342b3f964f7430dd581002f', 'f0952d0a1238feee4d82f27ccdf725ca4e9cba87e6dedfd493fb2ea015234fd6', 12505, 149),
    'docs/specs/issue88-supervisor-readiness/design.md': ('100644', 'a87dc6982b8806690a0bcbe86dd4bc98327ec519', '597f6fc0155eb28875bef06a8b5a8b980f06cfb369dcedac987c6408e0dd6da1', 3675, 34),
    'docs/specs/issue88-supervisor-readiness/requirements.md': ('100644', '6b0bf1d09db0c4458c2830eb98be8b31460d16a4', 'efd2cd849b3fbe6603b1395b1073c000ae0be9818c691762d6437c8a6710d253', 2582, 36),
    'docs/specs/issue88-supervisor-readiness/tasks.md': ('100644', '4cc83037966e6485aeacc95473f08d62d6ea6b37', '9aa283f3ed0e9eb877494e8213af09f7d44a2876b759ef970273dd2f4dfae345', 2387, 37),
    'scripts/rc_consumer_transport_supervisor_tests.py': ('100644', 'a9072b3d6b1ecbe3a69eaa1a60086986764e159d', '3c48ca1eba0b9d994109df4535271c0ef2253085e580cc419cabe8524af80dc3', 23636, 462),
    'scripts/rc_pretag_composition_tests.py': ('100644', 'a3183e9b20ac12afcbc8aabd310504166cc8ae9c', '77467ccefb25b3cb7208a27c39196acd6a9f21b9a247131de547b94a0aefd988', 36574, 490),
    'scripts/rc_pretag_staged_bytes_cases.py': ('100644', 'ff65c6e0784454b038267dc4b1d42d5bd9384b0e', '45e1741ca91431bfac233ca5241cd1a44acb5b5a5e00151f6e948a585a31b968', 32523, 447),
    'scripts/rc_pretag_staged_bytes_profile.py': ('100644', 'a2a3ba26aa53c5b83c92e27566339fbca15ba345', '434549cee84623f24c9eb3f75efa669ad71d8afc7d7833dd0e0672753c34e915', 51772, 223),
    'scripts/rc_pretag_supervisor_readiness_cases.py': ('100644', 'bed09c9968088d15d27ebd22b911a22f8214ae2f', 'a22ee7e82764bbacc55a0296e7903a2b29f889309d12330027fb19bde1d5ae71', 25541, 335),
}
FRAGMENTS = {
    '.github/workflows/issue88-publication-executor.yml': (
        (b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen two hundred sixty one cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n", b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen two hundred forty nine cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n"),
        (b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_supervisor_readiness_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              import rc_pretag_download_budget_cases as download_budget\n", b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_staged_bytes_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              import rc_pretag_download_budget_cases as download_budget\n"),
        (b"              import rc_pretag_checksum_budget_cases as checksum_budget\n              import rc_pretag_archive_budget_cases as archive_budget\n              import rc_pretag_staged_bytes_cases as staged_bytes\n              import rc_pretag_supervisor_readiness_cases as supervisor_readiness\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n", b"              import rc_pretag_checksum_budget_cases as checksum_budget\n              import rc_pretag_archive_budget_cases as archive_budget\n              import rc_pretag_staged_bytes_cases as staged_bytes\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n"),
        (b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'staged-bytes-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert staged_bytes.execution_valid(loaded, result)\n              names = supervisor_readiness.inventory()\n              suite = unittest.defaultTestLoader.loadTestsFromNames(names)\n              loaded = [test.id() for test in c._flatten(suite)]\n              with (evidence / 'supervisor-readiness-cases.log').open('w', encoding='utf-8') as output:\n                  result = unittest.TextTestRunner(stream=output, verbosity=2, resultclass=c.InventoryResult).run(suite)\n              receipt = {'loaded_ids': loaded, 'executed_ids': result.executed_ids, 'tests_run': result.testsRun,\n                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'supervisor-readiness-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert supervisor_readiness.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n", b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'staged-bytes-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert staged_bytes.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n"),
    ),
    'scripts/rc_consumer_transport_supervisor_tests.py': (
        (b"\n\n@contextmanager\ndef trickle(mode, data, *, progress=None):\n    server = socket.socket(); server.bind(('127.0.0.1', 0)); server.listen(1); server.settimeout(2)\n    stop, seen, errors = threading.Event(), [], []\n    def serve():\n", b"\n\n@contextmanager\ndef trickle(mode, data):\n    server = socket.socket(); server.bind(('127.0.0.1', 0)); server.listen(1); server.settimeout(2)\n    stop, seen, errors = threading.Event(), [], []\n    def serve():\n"),
        (b"                        connection.sendall(b'Content-Length: ' + str(len(data)).encode() + b'\\r\\n\\r\\n')\n                    else:\n                        connection.sendall(b'X-Slow: ')\n                if progress is not None:\n                    progress.append(time.monotonic())\n                for _ in range(160):\n                    if stop.wait(0.025):\n                        break\n                    connection.sendall(b'x')\n                    if progress is not None:\n                        progress.append(time.monotonic())\n                if not stop.is_set():\n                    if 'body' not in mode:\n                        headers = b'\\r\\nContent-Length: ' + str(len(data)).encode() + b'\\r\\n'\n", b"                        connection.sendall(b'Content-Length: ' + str(len(data)).encode() + b'\\r\\n\\r\\n')\n                    else:\n                        connection.sendall(b'X-Slow: ')\n                for _ in range(160):\n                    if stop.wait(0.025):\n                        break\n                    connection.sendall(b'x')\n                if not stop.is_set():\n                    if 'body' not in mode:\n                        headers = b'\\r\\nContent-Length: ' + str(len(data)).encode() + b'\\r\\n'\n"),
        (b"    def opener(self, mode='responses', port=None):\n        return Opener(self.redirect(), Response(200, self.data), mode=mode, port=port)\n\n    def failure(self, mode, code=None, opener=None, **kwargs):\n        opener = opener or self.opener(mode)\n        started = time.monotonic()\n        with patch.object(transport, 'TOTAL_TIMEOUT', 0.5), patch.object(transport, 'CLEANUP_TIMEOUT', 0.5):\n            with self.assertRaises(ConsumerError) as caught:\n                self.run_download(opener, **kwargs)\n        self.assertLess(time.monotonic() - started, 1.5)\n        self.assertIsNotNone(opener.process.poll())\n        self.assertIsNone(caught.exception.__context__)\n", b"    def opener(self, mode='responses', port=None):\n        return Opener(self.redirect(), Response(200, self.data), mode=mode, port=port)\n\n    def failure(self, mode, code=None, opener=None):\n        opener = opener or self.opener(mode)\n        started = time.monotonic()\n        with patch.object(transport, 'TOTAL_TIMEOUT', 0.5), patch.object(transport, 'CLEANUP_TIMEOUT', 0.5):\n            with self.assertRaises(ConsumerError) as caught:\n                self.run_download(opener)\n        self.assertLess(time.monotonic() - started, 1.5)\n        self.assertIsNotNone(opener.process.poll())\n        self.assertIsNone(caught.exception.__context__)\n"),
        (b"        self.data = b'x' * 160\n        self.artifact.update(size_in_bytes=len(self.data), digest='sha256:' + __import__('hashlib').sha256(self.data).hexdigest())\n        for mode in ('local_headers', 'local_body', 'local_api_headers', 'local_api_status', 'local_storage_status'):\n            progress = []\n            with self.subTest(mode=mode), trickle(mode, self.data, progress=progress) as (port, seen):\n                # Keep a full real half-second of drip after the selected response phase.\n                # Bound readiness separately; the owned logical deadline remains fixed.\n                ready_by = time.monotonic() + 0.9\n                readiness_failed = False\n                def clock():\n                    nonlocal readiness_failed\n                    phase = progress[0] if progress else None\n                    now = time.monotonic()\n                    if phase is None:\n                        readiness_failed |= now >= ready_by\n                    else:\n                        readiness_failed |= phase >= ready_by\n                    return 0.5 if readiness_failed else (now - phase if phase is not None else 0.0)\n                error = self.failure(mode, 'transport_deadline_exceeded', self.opener(mode, port),\n                                     clock=clock, deadline=0.5, check_active=lambda: None)\n                self.assertTrue(seen)\n                self.assertFalse(readiness_failed)\n                self.assertGreaterEqual(len(progress), 9)\n                self.assertLess(progress[0], ready_by)\n                self.assertGreaterEqual(progress[-1] - progress[0], 0.35)\n                self.assertGreaterEqual(time.monotonic() - progress[0], 0.5)\n                if not mode.startswith('local_api'):\n                    self.assertNotIn(b'authorization:', seen[0].lower())\n            # Each isolated invocation owns a fresh root/file.\n", b"        self.data = b'x' * 160\n        self.artifact.update(size_in_bytes=len(self.data), digest='sha256:' + __import__('hashlib').sha256(self.data).hexdigest())\n        for mode in ('local_headers', 'local_body', 'local_api_headers', 'local_api_status', 'local_storage_status'):\n            with self.subTest(mode=mode), trickle(mode, self.data) as (port, seen):\n                error = self.failure(mode, 'transport_deadline_exceeded', self.opener(mode, port))\n                self.assertTrue(seen)\n                if not mode.startswith('local_api'):\n                    self.assertNotIn(b'authorization:', seen[0].lower())\n            # Each isolated invocation owns a fresh root/file.\n"),
    ),
    'scripts/rc_pretag_composition_tests.py': (
        (b"        self.assertEqual(len(methods), 12)\n        digest = hashlib.sha256('\\n'.join(ast.dump(node, include_attributes=False) for node in methods).encode()).hexdigest()\n        self.assertEqual(digest, '9a204c5631142c9b2298b3eeaabdeba1e9148b19398984e736c96305a4e744e2')\n        self.assertEqual(_blob(integration_bytes('scripts/rc_consumer_transport_supervisor_tests.py', (ROOT / 'scripts/rc_consumer_transport_supervisor_tests.py').read_bytes())),\n                         'e45608f7ae523c25ea5d12cd4d24cbd56a3f1c12')\n\n    def test_finite_review_budgets(self):\n", b"        self.assertEqual(len(methods), 12)\n        digest = hashlib.sha256('\\n'.join(ast.dump(node, include_attributes=False) for node in methods).encode()).hexdigest()\n        self.assertEqual(digest, '9a204c5631142c9b2298b3eeaabdeba1e9148b19398984e736c96305a4e744e2')\n        self.assertEqual(_blob((ROOT / 'scripts/rc_consumer_transport_supervisor_tests.py').read_bytes()),\n                         'e45608f7ae523c25ea5d12cd4d24cbd56a3f1c12')\n\n    def test_finite_review_budgets(self):\n"),
    ),
    'scripts/rc_pretag_staged_bytes_cases.py': (
        (b"import rc_pretag_checksum_budget_cases as checksum_cases\nimport rc_pretag_archive_budget_cases as archive_cases\nimport rc_pretag_staged_bytes_profile as x\nfrom rc_pretag_supervisor_readiness_profile import normalize as readiness_bytes\n\nF_BINDING = ('f9d414b0c85348da79fee80c3b04bf5a06daf1d7', '57903a2751483c8b6e1aaa3879dce8173e77d647', ('e90e15fa8b6d527006b6c62a75eb2fcab6629f0f', '564a68d42463b3e3b526d875970dd631da2e3eec'))\n\n", b"import rc_pretag_checksum_budget_cases as checksum_cases\nimport rc_pretag_archive_budget_cases as archive_cases\nimport rc_pretag_staged_bytes_profile as x\n\nF_BINDING = ('f9d414b0c85348da79fee80c3b04bf5a06daf1d7', '57903a2751483c8b6e1aaa3879dce8173e77d647', ('e90e15fa8b6d527006b6c62a75eb2fcab6629f0f', '564a68d42463b3e3b526d875970dd631da2e3eec'))\n\n"),
        (b"        cls.fixture.__exit__(None, None, None)\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob(readiness_bytes(path, (c.ROOT / path).read_bytes()))) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n", b"        cls.fixture.__exit__(None, None, None)\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob((c.ROOT / path).read_bytes())) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n"),
        (b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1783, 1790, 15, 8))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (350, 350))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob(readiness_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes())))\n        for path, row in x.SOURCE_PINS.items():\n            data = readiness_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n", b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1783, 1790, 15, 8))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (350, 350))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob((c.ROOT / x.PROFILE).read_bytes()))\n        for path, row in x.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n"),
        (b"        self.bad_content(self.changed('services/cloud-agent/src/main.rs', b'changed\\n'))\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (1800, 1753))\n        data = {path: readiness_bytes(path, (c.ROOT / path).read_bytes()) for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'staged_bytes_delta_budget')\n        budgets()\n", b"        self.bad_content(self.changed('services/cloud-agent/src/main.rs', b'changed\\n'))\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (1800, 1753))\n        data = {path: (c.ROOT / path).read_bytes() for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'staged_bytes_delta_budget')\n        budgets()\n"),
        (b"        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        self.assertEqual(len(x.FRAGMENTS), 8)\n        for path in x.BASE_PINS:\n            current, frozen = readiness_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('io.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')), patch('subprocess.Popen', side_effect=AssertionError('process forbidden')), patch('tempfile.TemporaryDirectory', side_effect=AssertionError('extraction forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = readiness_bytes(x.DISPATCHER, (c.ROOT / x.DISPATCHER).read_bytes())\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n", b"        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        self.assertEqual(len(x.FRAGMENTS), 8)\n        for path in x.BASE_PINS:\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('io.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')), patch('subprocess.Popen', side_effect=AssertionError('process forbidden')), patch('tempfile.TemporaryDirectory', side_effect=AssertionError('extraction forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = (c.ROOT / x.DISPATCHER).read_bytes()\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n"),
        (b"                    self.assertEqual(x.normalize(path, prior), prior)\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = readiness_bytes(path, (c.ROOT / path).read_bytes())\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n", b"                    self.assertEqual(x.normalize(path, prior), prior)\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = (c.ROOT / path).read_bytes()\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n"),
        (b"                    if bad == prior: continue\n                    with self.assertRaises(AssertionError): x.normalize(path, bad)\n        path = 'scripts/rc_pretag_checksum_budget_cases.py'\n        current = readiness_bytes(path, (c.ROOT / path).read_bytes())\n        bad = current.replace(b'self.assertEqual(', b'self.assertNotEqual(', 1)\n        self.assertNotEqual(bad, current)\n        with patch.dict(x.SOURCE_PINS, {path: ('100644', *o.pin(bad), len(bad), len(bad.splitlines()))}), self.assertRaises(AssertionError):\n", b"                    if bad == prior: continue\n                    with self.assertRaises(AssertionError): x.normalize(path, bad)\n        path = 'scripts/rc_pretag_checksum_budget_cases.py'\n        current = (c.ROOT / path).read_bytes()\n        bad = current.replace(b'self.assertEqual(', b'self.assertNotEqual(', 1)\n        self.assertNotEqual(bad, current)\n        with patch.dict(x.SOURCE_PINS, {path: ('100644', *o.pin(bad), len(bad), len(bad.splitlines()))}), self.assertRaises(AssertionError):\n"),
        (b"            with self.assertRaises(AssertionError):\n                x.normalize(path, current)\n        path = 'scripts/rc_pretag_checksum_budget_cases.py'\n        current, frozen = readiness_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n        self.assertEqual(x.normalize(path, current), frozen)\n        row = ('100644', *o.pin(frozen), len(frozen), len(frozen.splitlines()))\n        self.assertEqual(self.original[path], (row[0], 'blob', row[1]))\n", b"            with self.assertRaises(AssertionError):\n                x.normalize(path, current)\n        path = 'scripts/rc_pretag_checksum_budget_cases.py'\n        current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n        self.assertEqual(x.normalize(path, current), frozen)\n        row = ('100644', *o.pin(frozen), len(frozen), len(frozen.splitlines()))\n        self.assertEqual(self.original[path], (row[0], 'blob', row[1]))\n"),
        (b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse(readiness_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes()).decode())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n    def test_original1403_strict303_consumer452_ids_and_bodies_are_preserved(self):\n        original = [item for group in lc.GROUPS for item in lc.inventory(group)] + lc.ids(y.CLASS) + old_cases.inventory() + previous_cases.inventory() + final_cases.inventory() + download_cases.inventory() + staging_cases.inventory() + checksum_cases.inventory() + archive_cases.inventory()\n", b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse((c.ROOT / x.PROFILE).read_text())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n    def test_original1403_strict303_consumer452_ids_and_bodies_are_preserved(self):\n        original = [item for group in lc.GROUPS for item in lc.inventory(group)] + lc.ids(y.CLASS) + old_cases.inventory() + previous_cases.inventory() + final_cases.inventory() + download_cases.inventory() + staging_cases.inventory() + checksum_cases.inventory() + archive_cases.inventory()\n"),
        (b"        changed = set()\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = readiness_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            before, after = methods(frozen), methods(current)\n            self.assertEqual(before.keys(), after.keys(), path)\n", b"        changed = set()\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            before, after = methods(frozen), methods(current)\n            self.assertEqual(before.keys(), after.keys(), path)\n"),
        (b'        self.assertEqual(changed, {(module, name) for module, names in allowed.items() for name in names})\n        self.assertFalse(set(original) & set(inventory()))\n    def test_readonly_workflow_and_held_sources_remain_bounded(self):\n        text = readiness_bytes(x.WORKFLOW, (c.ROOT / x.WORKFLOW).read_bytes()).decode()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n', b'        self.assertEqual(changed, {(module, name) for module, names in allowed.items() for name in names})\n        self.assertFalse(set(original) & set(inventory()))\n    def test_readonly_workflow_and_held_sources_remain_bounded(self):\n        text = (c.ROOT / x.WORKFLOW).read_text()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n'),
        (b"                'scripts/rc_consumer_transport.py', 'scripts/rc_consumer_transport_worker.py',\n                'scripts/rc_consumer_proof_fixtures.py', 'scripts/rc_consumer_default_worker_proof.py', 'scripts/rc_consumer_default_worker_proof_tests.py',\n                'scripts/rc_consumer_c_93c2ad95_io.txt', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual(x.normalize(path, readiness_bytes(path, (c.ROOT / path).read_bytes())), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n    def test_new30_inventory_and_exceptional_outcomes_reject(self):\n        loaded = inventory()\n", b"                'scripts/rc_consumer_transport.py', 'scripts/rc_consumer_transport_worker.py',\n                'scripts/rc_consumer_proof_fixtures.py', 'scripts/rc_consumer_default_worker_proof.py', 'scripts/rc_consumer_default_worker_proof_tests.py',\n                'scripts/rc_consumer_c_93c2ad95_io.txt', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual(x.normalize(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n    def test_new30_inventory_and_exceptional_outcomes_reject(self):\n        loaded = inventory()\n"),
    ),
    'scripts/rc_pretag_staged_bytes_profile.py': (
        (b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'staged_bytes inverse input\'\n    from rc_pretag_supervisor_readiness_profile import normalize as readiness_bytes\n    current = readiness_bytes(path, current)\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n', b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'staged_bytes inverse input\'\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n'),
        (b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    import rc_pretag_supervisor_readiness_profile as readiness\n    selected = readiness.select(ref, root, git, entries, historical, release, release_tree, documents)\n    if selected is not None:\n        return selected\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n', b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n'),
    ),
}
# END SEALED SOURCE
DISPATCH = b'    import rc_pretag_supervisor_readiness_profile as readiness\n    selected = readiness.select(ref, root, git, entries, historical, release, release_tree, documents)\n    if selected is not None:\n        return selected\n'
NORMALIZE = b'    from rc_pretag_supervisor_readiness_profile import normalize as readiness_bytes\n    current = readiness_bytes(path, current)\n'
NEW_CASES = {
    'rc_pretag_supervisor_readiness_cases.SupervisorReadinessCompositionCases': ('test_exact_f_identity_and_fresh_historical_validation', 'test_only_exact_d_i_j_topology_is_accepted', 'test_all_ten_paths_modes_pins_and_entry_counts_are_exact', 'test_individual_and_total_budgets_fail_closed', 'test_five_inverses_restore_complete_f_bytes', 'test_sixteen_historical_identities_are_exact', 'test_missing_duplicate_outside_binary_and_assertion_edits_reject', 'test_selected_historical_and_release_content_errors_are_terminal', 'test_actual_candidate_validation_is_never_cached', 'test_original1433_strict303_consumer452_ids_and_assertions_are_preserved', 'test_sustained_phase_readiness_and_bounded_failure_contracts_are_preserved', 'test_readonly_workflow_inventory_and_exceptional_outcomes_are_exact'),
}
CLASS = 'rc_pretag_supervisor_readiness_cases.SupervisorReadinessCompositionCases'
NAMES = NEW_CASES[CLASS]
DIGEST = 'eec151594feb2790312c59acb94ac4df164d39c4919327fc2e8213547f40466e'


def normalize(path, current):
    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""
    assert type(path) is str and type(current) is bytes, 'supervisor_readiness inverse input'
    if path not in BASE_PINS:
        return current
    identity = o.pin(current)
    baseline = BASE_PINS[path]
    if identity == baseline[1:3] or identity in PRIOR_PINS.get(path, ()):
        return current
    row = SOURCE_PINS[path]
    assert (identity, len(current), len(current.splitlines())) == (row[1:3], row[3], row[4]), path
    restored = current
    for before, after in reversed(FRAGMENTS[path]):
        assert before and restored.count(before) == 1, 'supervisor_readiness fragment missing or duplicated'
        restored = restored.replace(before, after, 1)
    assert (o.pin(restored), len(restored), len(restored.splitlines())) == (
        baseline[1:3], baseline[3], baseline[4]), 'complete supervisor_readiness F inverse'
    return restored


def topology(ref, root, git, release):
    """Only D[M], I[M,D], J[R,I]; no correction chains or ancestry inference."""
    if release != p.R:
        raise o.TopologyError('supervisor_readiness_release_anchor')
    parents = o._parents(ref, root, git)
    if parents == [M]:
        kind, tip, source = 'nonrelease', ref, ref
    elif len(parents) == 2 and parents[0] == M:
        kind, tip, source = 'nonrelease', ref, parents[1]
    elif len(parents) == 2 and parents[0] == p.R:
        kind, tip = 'release', parents[1]
        feature_parents = o._parents(tip, root, git)
        if len(feature_parents) != 2 or feature_parents[0] != M:
            raise o.TopologyError('supervisor_readiness_feature_parents')
        source = feature_parents[1]
    else:
        raise o.TopologyError('supervisor_readiness_candidate_parents')
    if o._parents(source, root, git) != [M]:
        raise o.TopologyError('supervisor_readiness_candidate_parent')
    return kind, tip, source


def content(ref, root, git, entries, historical, release, release_tree, documents):
    """Fresh immutable M admission, exact candidate pins and complete reviewed delta."""
    assert (release, release_tree, documents) == (p.R, p.R_TREE, p.R_DOCUMENTS)
    assert tuple(o._parents(M, root, git)) == M_PARENTS, 'supervisor_readiness M parents'
    assert git('rev-parse', M + '^{tree}', root=root).decode().strip() == M_TREE, 'supervisor_readiness M tree'
    raw = git('cat-file', 'commit', M, root=root)
    assert (len(raw), hashlib.sha256(raw).hexdigest()) == M_RAW, 'supervisor_readiness M raw'
    baseline = p.selected_profile(M, root, git, entries, historical, release, release_tree, documents)
    assert baseline == entries(M, root) and len(baseline) == 1790
    actual, paths = entries(ref, root), CAPS.keys()
    assert len(paths) == 10 and SOURCE_PINS.keys() == paths - {PROFILE}
    assert baseline.keys() & paths == BASE_PINS.keys() and len(BASE_PINS) == 5
    assert FRAGMENTS.keys() == BASE_PINS.keys() and PRIOR_PINS.keys() <= BASE_PINS.keys()
    assert len(PRIOR_PINS) == 2 and sum(map(len, PRIOR_PINS.values())) == 16
    assert actual.keys() == baseline.keys() | paths and len(actual) == 1795
    assert {path for path in actual if actual[path] != baseline.get(path)} == paths
    assert all(actual[path] == value for path, value in baseline.items() if path not in paths)
    assert all(actual[path][:2] == ('100644', 'blob') for path in paths)
    assert all(actual[path] == (row[0], 'blob', row[1]) for path, row in SOURCE_PINS.items())
    data = {path: git('cat-file', 'blob', actual[path][2], root=root) for path in paths}
    for path, (mode, blob, digest, size, count) in SOURCE_PINS.items():
        assert mode == '100644' and o.pin(data[path]) == (blob, digest), path
        assert (len(data[path]), len(data[path].splitlines())) == (size, count), path
    for path, row in BASE_PINS.items():
        assert baseline[path] == (row[0], 'blob', row[1]), path
        assert normalize(path, data[path]) == git('cat-file', 'blob', baseline[path][2], root=root), path
    p.authenticated._budgets(ref, M, root, git, data, CAPS, DELTA_LIMIT, 'supervisor_readiness_delta_budget')
    return actual


def select(ref, root, git, entries, historical, release, release_tree, documents):
    """Only topology mismatch delegates; selected and historical content errors escape."""
    ref = o._commit(ref, root, git)
    try:
        kind, tip, source = topology(ref, root, git, release)
    except o.TopologyError:
        return None
    expected = content(source, root, git, entries, historical, release, release_tree, documents)
    assert entries(tip, root) == expected
    if kind == 'release':
        return o.release_content(ref, expected, root, git, entries, release, release_tree, documents)
    return expected
