"""Finite staging-budget source admission; independent complete-tree review binds this module."""
import rc_pretag_ownership_profile as o
import rc_pretag_publication_profile as p

M = '981d7b23af1c5c8174352c4564aa65b1557cc546'
M_TREE = 'c3d7780ce761dac4da71d97a010381ec5074f69f'
M_PARENTS = ('7de3244adc367fa60463d1e3b64c92f211d2fda8', 'd52937c98d441f3ee49eb9decd9101cade654748')
PROFILE = 'scripts/rc_pretag_staging_budget_profile.py'
CASES = 'scripts/rc_pretag_staging_budget_cases.py'
DISPATCHER = 'scripts/rc_pretag_download_budget_profile.py'
WORKFLOW = '.github/workflows/issue88-publication-executor.yml'
CAPS = {
    'scripts/rc_publication_executor.py': (300, 70),
    'scripts/rc_publication_stage.py': (350, 80),
    'scripts/rc_artifact_consumer.py': (270, 20),
    'scripts/rc_pretag_composition_tests.py': (490, 4),
    'scripts/rc_pretag_download_budget_profile.py': (220, 6),
    'scripts/rc_pretag_download_budget_cases.py': (425, 40),
    '.github/workflows/issue88-publication-executor.yml': (120, 24),
    'scripts/rc_publication_staging_budget_cases.py': (480, 480),
    'scripts/rc_pretag_staging_budget_profile.py': (400, 400),
    'scripts/rc_pretag_staging_budget_cases.py': (440, 440),
    'docs/specs/issue88-staging-budget/requirements.md': (40, 40),
    'docs/specs/issue88-staging-budget/design.md': (70, 70),
    'docs/specs/issue88-staging-budget/tasks.md': (60, 60),
}
BASE_PINS = {
    'scripts/rc_publication_executor.py': ('100644', '2e22b0b14013dbac09d21a3daceb425c371c2932', '9adf8f0b43f85d276f450e194cc5bb553a67485082b9729fcc9a3b4d7d7951af', 9957, 235),
    'scripts/rc_publication_stage.py': ('100644', 'b4ecb6e7400c1937b68f1ac960e2f6f0ecda4b65', 'b5d0e8f575f24e9977989b183f7ca415bb7cdf0e6142d645b98ddeeab12c6216', 18170, 295),
    'scripts/rc_artifact_consumer.py': ('100644', '1475ffd862c75effb4f4f8f401f37e816ba714ce', '3408807349f305037799025810bd109f4f1e95a0c53a00bd80bf69a2cfc145ec', 14172, 249),
    'scripts/rc_pretag_composition_tests.py': ('100644', '2bebb78514e8e7c8358e5bac4c2cbfb2d09ecd8b', 'b285be0f99bfa93aaa21179c8b97a248c3afbfa4c7b977fa3e52e22d041eb4ce', 36423, 490),
    'scripts/rc_pretag_download_budget_profile.py': ('100644', '4ddc999311581c9d870b7e135caf2334a39cd50e', '7f8d117e4b753004cfde4b83e3ae20068e7c9179f380d45ff0f0de31e725e63a', 49375, 211),
    'scripts/rc_pretag_download_budget_cases.py': ('100644', '2fd53208f80ce4078e851165b28bf737e47081e5', '88e00aeed01bdcb2e43d08ee597bd79152f8314b2362696112cabe2d3d19e489', 29469, 410),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'a81e9404bae5e4a56599eb0455026c207acbdc27', 'ef64753deb51f2260812bf136ad4bca0d811bc84e61e601e80697fdef314181c', 7601, 99),
}
PRIOR_PINS = {
    'scripts/rc_pretag_composition_tests.py': (('56549d0a55f3162dfb7b3ed993e4ddcff18ff69f', '105f8562da48ff4557898e017ead8762f55e55357a664e1372e1443d25f217e2'), ('988c4be1175b68feecc2c38f8aee7f932e4589e2', 'ff5e95e6ff14416aa969e1c9dad9e729c96c3aa624da63af4ff93c9edc397694'), ('99483e8545add6209aee035b7460d5b56c023a82', 'f0cf5e2ff2739efd976125d893bf9cd58a5c1d0706a4b9cf95d998811b706488'), ('67e97761d6570869e64ea04276b635cd89f3ccc1', '5bf44aac60240fb6ee5d0af5afd82a8aa16ff4008ec78530cab937753e47a029'), ('f306ba3902577acc5f8d3b8c0537b1921050e062', '061036efcb39239f3251d3f212472166c2f5f2b1a2d37c3cc9ea0e75da8b4a4a'), ('959bddf9d5f32767e033418bb4823e8c7ef32a77', '132fb6b5760fbefdb0d728f8400d3ee8544c6218329483e5ec5828d2f6b81cf6'), ('6aceb93ede42cecac841e12d30bd35ae156ba8ef', '61098cd058653f1585ae35bcec620ab8a209535cf8b81b78dcbb47b62e88c10c'), ('00d8e657375a479779d7c06ef33cb847ff9f49d0', 'e8c1ac54d30a4030f9b843aeee1c1ff1a94013641f533f1e97e35603d25e8c74')),
    'scripts/rc_publication_executor.py': (('a64cf4c91ad43c0efd35e0a5c8c0d1de96cdfd11', 'e13ceb317de92c724cecafac06875659f0eacd8e66aa2a76c964fdded176a02e'),),
    '.github/workflows/issue88-publication-executor.yml': (('f3cf8b1e3f337204f423ae200e667aaf9d34e3f8', '5fedc956307b75e7d59c3f5aeda153b6e3e64dd618700141862149c3fda37d7a'), ('d06143c505bf739dfd4336ea97c20b5850d15128', 'ceb14dd7012995f1d3400e1eb7dfc24533b564cd9a039e2592c74b153d036634'), ('c6cc466d9d2520b668508e6fbd9754f1ac1cc7ef', '850aea3f1d81c00322f8c8ca1adf84a5abddb5c75d916066394f41a521397e4e')),
}
DELTA_LIMIT = 1800
# BEGIN SEALED SOURCE
SOURCE_PINS = {
    'scripts/rc_publication_executor.py': ('100644', 'fa8ae2fe35b4b8c730964f557f9c294e81bbefc7', '7af479ea9c1f7ae235e34ced08f5854209717edb0e0a628d06a0e2171892ccc6', 10762, 251),
    'scripts/rc_publication_stage.py': ('100644', 'ac41bd2c99fcabdb81eb9b1125f3aaca937baa80', 'e77ef98244c25e0bab1b136d0e6df1c0dbbf6fec24bec84e992f9c34dc99c313', 19163, 315),
    'scripts/rc_artifact_consumer.py': ('100644', '0dfd9bc7fb13e6504d76a9c9f374b55d3daf1123', '963d36b5f5f3408e84c73482086e258c34f5ff3d5e27e6abed9083a7a51d44ee', 14358, 251),
    'scripts/rc_pretag_composition_tests.py': ('100644', '5c9b6e051f2e8e34a1a84d00e4cd9465627ed670', 'a0504babffa24689fa16d29d4832778a6067783c0ee82fe477f59919a12f2a96', 36502, 490),
    'scripts/rc_pretag_download_budget_profile.py': ('100644', '1492ddca36a41c4479754cf231cd8ee9633a9011', '03485e9746b45108fcf53cdd076f7866a5dc7df1b91e46ab33a5044587dd702b', 49703, 217),
    'scripts/rc_pretag_download_budget_cases.py': ('100644', 'ac8c81f2cccd91fe33fb5dd76236c54824830f0a', '93afdafab5eda468287e43ff775a0c7a355b92c46a0fb2917c0a781720b4184c', 29816, 411),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'a61797b57dcba000d238dbd2c224247ec077cdbc', '28601d9ded709b55ccad36f966a106e2912d67c48ec47833b9b519e1524045dc', 8575, 109),
    'scripts/rc_publication_staging_budget_cases.py': ('100644', '0b9728629451ac26d6f184214399a379e49187eb', 'efb03d93c70a061d910d10642c0239ad048bbe6db643e4426d1cde201e2c1255', 18792, 361),
    'scripts/rc_pretag_staging_budget_cases.py': ('100644', '5f0d773cbf81b2650d2a9538aff654bceb05f717', '163ede10fba1845e31bddcc44b814de309fcff438752c5e10471a7cd3c6fdf54', 27947, 382),
    'docs/specs/issue88-staging-budget/requirements.md': ('100644', '27fb50f22851fc8d183da7f86176d30c1701634a', 'e155573682d44b715c78a2aefdc4464b090e95cc612acd08872cb397a79c69c6', 3394, 37),
    'docs/specs/issue88-staging-budget/design.md': ('100644', '86b07fe3c88583af69247a3cf263ccdd398e4892', 'bffba13b6d63a01100e1f38bbbb0a5bda398c881435aa2818d5bbe47e9ab2842', 5285, 46),
    'docs/specs/issue88-staging-budget/tasks.md': ('100644', '3aeb0ed68bc45b11451d10466d63e4c979233894', 'bc5157533df6971ee1be26eb9e5ee1e1a3b294e5a1e603f1217b6f1c76c0e5b7', 3409, 43),
}
FRAGMENTS = {
    'scripts/rc_publication_executor.py': (
        (b'\nimport rc_publication_contract as core\nimport rc_publication_github as wire\nfrom rc_consumer_io import ConsumerError\nfrom rc_publication_stage import Selection, stage_selected\n\nOPERATION_SECONDS = 300\n', b'\nimport rc_publication_contract as core\nimport rc_publication_github as wire\nfrom rc_publication_stage import Selection, stage_selected\n\nOPERATION_SECONDS = 300\n'),
        (b"            wire._authenticate(self._selection, self._api, check_active=self._check_active, deadline=self._deadline)\n            wire._remote_constraint(self._selection.subject)\n            self._stage = stage_selected(self._root, self._selection, self._api,\n                temporary_parent=self._temporary_parent, deadline=self._deadline, check_active=self._check_active)\n            self._stage.__enter__()\n            self._check_active()\n            self._transition = core.start(self._stage.subject, self._stage.plan)\n        except BaseException as error:\n            self._activation_outcome = 'blocked_no_effect'\n            transport_code = None\n            try:\n                if isinstance(error, ConsumerError):\n                    transport_code = error.code\n            except BaseException:\n                pass\n            if type(transport_code) is not str:\n                transport_code = None\n            if transport_code == 'transport_cleanup_uncertain':\n                self._cleanup_failed = True\n            failed = self._dispose()\n            code = error.code if isinstance(error, wire.WireFailure) else 'adapter_error'\n            if transport_code is not None:\n                code = {'transport_deadline_exceeded': 'timeout',\n                        'transport_cancelled': 'cancelled'}.get(transport_code, 'adapter_error')\n            if failed:\n                code = 'adapter_error'\n            raise wire.WireFailure(code, 'none') from None\n\n    def _check_active(self):\n", b"            wire._authenticate(self._selection, self._api, check_active=self._check_active, deadline=self._deadline)\n            wire._remote_constraint(self._selection.subject)\n            self._stage = stage_selected(self._root, self._selection, self._api,\n                                         temporary_parent=self._temporary_parent)\n            self._stage.__enter__()\n            self._check_active()\n            self._transition = core.start(self._stage.subject, self._stage.plan)\n        except BaseException as error:\n            self._activation_outcome = 'blocked_no_effect'\n            self._dispose()\n            code = error.code if isinstance(error, wire.WireFailure) else 'adapter_error'\n            raise wire.WireFailure(code, 'none') from None\n\n    def _check_active(self):\n"),
        (b'    def _dispose(self):\n        """Retire each owner once; never retry a possibly closed descriptor."""\n        self._closed = True\n        failed = self._cleanup_failed or bool(self._stage and self._stage._cleanup_failed)\n        stage, self._stage = self._stage, None\n        api, self._api = self._api, None\n        for owner in (stage, api):\n', b'    def _dispose(self):\n        """Retire each owner once; never retry a possibly closed descriptor."""\n        self._closed = True\n        failed = self._cleanup_failed\n        stage, self._stage = self._stage, None\n        api, self._api = self._api, None\n        for owner in (stage, api):\n'),
    ),
    'scripts/rc_publication_stage.py': (
        (b"\n\nclass StagedAssets:\n    def __init__(self, root, selection, api, temporary_parent, *, deadline=None, check_active=None):\n        need(type(selection) is Selection, 'invalid_publication_selection')\n        self._selection = deepcopy(selection)\n        self._selection.__post_init__()\n        self.subject, self._root, self._api = self._selection.subject, Path(root), api\n        self._parent, self._stack, self._roots, self._handles = temporary_parent, ExitStack(), [], []\n        self._entered = self._closed = False\n        self._deadline, self._check_active = deadline, check_active\n        self._cleanup_failed = False\n\n    def __enter__(self):\n        need(not self._entered and not self._closed, 'stage_lifetime')\n", b"\n\nclass StagedAssets:\n    def __init__(self, root, selection, api, temporary_parent):\n        need(type(selection) is Selection, 'invalid_publication_selection')\n        self._selection = deepcopy(selection)\n        self._selection.__post_init__()\n        self.subject, self._root, self._api = self._selection.subject, Path(root), api\n        self._parent, self._stack, self._roots, self._handles = temporary_parent, ExitStack(), [], []\n        self._entered = self._closed = False\n\n    def __enter__(self):\n        need(not self._entered and not self._closed, 'stage_lifetime')\n"),
        (b"                self._roots.append(root)\n                return root\n            receipt_download, receipts, download, bundle, cloud, self._output = (fresh() for _ in range(6))\n            budget = {} if self._deadline is None and self._check_active is None else dict(\n                deadline=self._deadline, check_active=self._check_active)\n            path = consumer.transport.download_artifact_zip(self._api, self._observation[3], receipt_download, **budget)\n            snapshot._call(_receipts, path, receipts)\n            self.plan_bytes, self.provenance_bytes = (receipts.read(name) for name in ('rc-asset-plan.json', 'RC_PROVENANCE.json'))\n            need(hashlib.sha256(self.plan_bytes).hexdigest() == self.subject.plan_sha256, 'original_plan_digest_mismatch')\n", b"                self._roots.append(root)\n                return root\n            receipt_download, receipts, download, bundle, cloud, self._output = (fresh() for _ in range(6))\n            path = consumer.transport.download_artifact_zip(self._api, self._observation[3], receipt_download)\n            snapshot._call(_receipts, path, receipts)\n            self.plan_bytes, self.provenance_bytes = (receipts.read(name) for name in ('rc-asset-plan.json', 'RC_PROVENANCE.json'))\n            need(hashlib.sha256(self.plan_bytes).hexdigest() == self.subject.plan_sha256, 'original_plan_digest_mismatch')\n"),
        (b"            runs, metadata, _, _ = self._observation\n            producer = snapshot.derive_final_producer(dict(source_sha=self.subject.source.source_sha,\n                source_tree=self.subject.source.source_tree, version=self.subject.source.version), runs, metadata)\n            content = consumer._verify_bundle_bytes(self._root, self._api, runs, metadata, producer, download, bundle, cloud, **budget)\n            snapshot._call(_provenance, self.subject, self._observation, content, provenance)\n            fixed = (*consumer.payloads(producer.version), ('RC_PROVENANCE.json', 'provenance', 'application/json'),\n                     (f'SHA256SUMS_{producer.version}.txt', 'checksums', 'text/plain'))\n", b"            runs, metadata, _, _ = self._observation\n            producer = snapshot.derive_final_producer(dict(source_sha=self.subject.source.source_sha,\n                source_tree=self.subject.source.source_tree, version=self.subject.source.version), runs, metadata)\n            content = consumer._verify_bundle_bytes(self._root, self._api, runs, metadata, producer, download, bundle, cloud)\n            snapshot._call(_provenance, self.subject, self._observation, content, provenance)\n            fixed = (*consumer.payloads(producer.version), ('RC_PROVENANCE.json', 'provenance', 'application/json'),\n                     (f'SHA256SUMS_{producer.version}.txt', 'checksums', 'text/plain'))\n"),
        (b"            self._identities = tuple((os.fstat(h.fileno()).st_dev, os.fstat(h.fileno()).st_ino) for h in self._handles)\n            self.revalidate()\n            return self\n        except BaseException as error:\n            uncertain = False\n            try:\n                code = error.code if isinstance(error, ConsumerError) else None\n                uncertain = type(code) is str and code == 'transport_cleanup_uncertain'\n            except BaseException:\n                pass\n            if uncertain:\n                self._cleanup_failed = True\n            try:\n                self.close()\n            except BaseException:\n                if not uncertain:\n                    raise\n            raise\n\n    def revalidate(self):\n", b'            self._identities = tuple((os.fstat(h.fileno()).st_dev, os.fstat(h.fileno()).st_ino) for h in self._handles)\n            self.revalidate()\n            return self\n        except BaseException:\n            self.close()\n            raise\n\n    def revalidate(self):\n'),
        (b'    def close(self):\n        if not self._closed:\n            self._closed = True\n            try:\n                self._stack.close()\n            except BaseException:\n                self._cleanup_failed = True\n                raise\n\n    def __exit__(self, *_):\n        self.close()\n\n\ndef stage_selected(root, selection, api, *, temporary_parent, deadline=None, check_active=None):\n    return StagedAssets(root, selection, api, temporary_parent, deadline=deadline, check_active=check_active)\n', b'    def close(self):\n        if not self._closed:\n            self._closed = True\n            self._stack.close()\n\n    def __exit__(self, *_):\n        self.close()\n\n\ndef stage_selected(root, selection, api, *, temporary_parent):\n    return StagedAssets(root, selection, api, temporary_parent)\n'),
    ),
    'scripts/rc_artifact_consumer.py': (
        (b'    return plan\n\n\ndef _verify_bundle_bytes(root, api, selection, metadata, producer, download, bundle, cloud, *,\n                         opener=None, deadline=None, check_active=None):\n    budget = {} if deadline is None and check_active is None else dict(deadline=deadline, check_active=check_active)\n    path = transport.download_artifact_zip(api, metadata, download, opener=opener, **budget)\n    snapshot.revalidate_download(api, selection, metadata)\n    archive.extract_bounded_zip(path, bundle, [name for name, _, _ in payloads(producer.version)])\n    archive.verify_checksum_inventory(bundle)\n', b'    return plan\n\n\ndef _verify_bundle_bytes(root, api, selection, metadata, producer, download, bundle, cloud, *, opener=None):\n    path = transport.download_artifact_zip(api, metadata, download, opener=opener)\n    snapshot.revalidate_download(api, selection, metadata)\n    archive.extract_bounded_zip(path, bundle, [name for name, _, _ in payloads(producer.version)])\n    archive.verify_checksum_inventory(bundle)\n'),
    ),
    'scripts/rc_pretag_composition_tests.py': (
        (b"        path = 'scripts/rc_artifact_consumer.py'\n        original = _git('show', BASE + ':' + path)\n        self.assertEqual((_blob(original), hashlib.sha256(original).hexdigest()), NARROW[path])\n        self.assertEqual(_reconstruct_consumer(integration_bytes(path, (ROOT / path).read_bytes()).decode('utf-8')).encode(), original)\n\n    def test_extraction_mutations_do_not_reconstruct_j(self):\n        text = (ROOT / 'scripts/rc_consumer_snapshot.py').read_bytes().decode('utf-8')\n        for statement in PURE_VALIDATION:\n            with self.assertRaises(AssertionError):\n                _reconstruct_snapshot(_replace_once(text, SNAPSHOT_EXTRA, SNAPSHOT_EXTRA.replace(statement, '')))\n        text = integration_bytes('scripts/rc_artifact_consumer.py', (ROOT / 'scripts/rc_artifact_consumer.py').read_bytes()).decode('utf-8')\n        for statement in BYTE_BODY.splitlines(True):\n            with self.assertRaises(AssertionError):\n                _reconstruct_consumer(_replace_once(text, BYTE_HELPER, BYTE_HELPER.replace(statement, '')))\n", b"        path = 'scripts/rc_artifact_consumer.py'\n        original = _git('show', BASE + ':' + path)\n        self.assertEqual((_blob(original), hashlib.sha256(original).hexdigest()), NARROW[path])\n        self.assertEqual(_reconstruct_consumer((ROOT / path).read_bytes().decode('utf-8')).encode(), original)\n\n    def test_extraction_mutations_do_not_reconstruct_j(self):\n        text = (ROOT / 'scripts/rc_consumer_snapshot.py').read_bytes().decode('utf-8')\n        for statement in PURE_VALIDATION:\n            with self.assertRaises(AssertionError):\n                _reconstruct_snapshot(_replace_once(text, SNAPSHOT_EXTRA, SNAPSHOT_EXTRA.replace(statement, '')))\n        text = (ROOT / 'scripts/rc_artifact_consumer.py').read_bytes().decode('utf-8')\n        for statement in BYTE_BODY.splitlines(True):\n            with self.assertRaises(AssertionError):\n                _reconstruct_consumer(_replace_once(text, BYTE_HELPER, BYTE_HELPER.replace(statement, '')))\n"),
    ),
    'scripts/rc_pretag_download_budget_profile.py': (
        (b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'download inverse input\'\n    from rc_pretag_staging_budget_profile import normalize as staging_bytes\n    current = staging_bytes(path, current)\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n', b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'download inverse input\'\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n'),
        (b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    import rc_pretag_staging_budget_profile as staging\n    selected = staging.select(ref, root, git, entries, historical, release, release_tree, documents)\n    if selected is not None:\n        return selected\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n', b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n'),
    ),
    'scripts/rc_pretag_download_budget_cases.py': (
        (b"import rc_pretag_integration_admission_cases as previous_cases\nimport rc_pretag_final_admission_cases as final_cases\nimport rc_pretag_download_budget_profile as x\nfrom rc_pretag_staging_budget_profile import normalize as staging_bytes\n\ndef inventory():\n    expected = [cls + '.' + name for cls, names in x.NEW_CASES.items() for name in names]\n", b"import rc_pretag_integration_admission_cases as previous_cases\nimport rc_pretag_final_admission_cases as final_cases\nimport rc_pretag_download_budget_profile as x\n\ndef inventory():\n    expected = [cls + '.' + name for cls, names in x.NEW_CASES.items() for name in names]\n"),
        (b"        cls.fixture.__exit__(None, None, None)\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob(staging_bytes(path, (c.ROOT / path).read_bytes()))) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n", b"        cls.fixture.__exit__(None, None, None)\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob((c.ROOT / path).read_bytes())) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n"),
        (b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1758, 1764, 14, 8))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (400, 400))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob(staging_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes())))\n        for path, row in x.SOURCE_PINS.items():\n            data = staging_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n", b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1758, 1764, 14, 8))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (400, 400))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob((c.ROOT / x.PROFILE).read_bytes()))\n        for path, row in x.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n"),
        (b"        self.bad_content(self.changed('services/cloud-agent/src/main.rs', b'changed\\n'))\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (2000, 1823))\n        data = {path: staging_bytes(path, (c.ROOT / path).read_bytes()) for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'download_delta_budget')\n        budgets()\n", b"        self.bad_content(self.changed('services/cloud-agent/src/main.rs', b'changed\\n'))\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (2000, 1823))\n        data = {path: (c.ROOT / path).read_bytes() for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'download_delta_budget')\n        budgets()\n"),
        (b"        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        self.assertEqual(len(x.FRAGMENTS), 8)\n        for path in x.BASE_PINS:\n            current, frozen = staging_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = staging_bytes(x.DISPATCHER, (c.ROOT / x.DISPATCHER).read_bytes())\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n", b"        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        self.assertEqual(len(x.FRAGMENTS), 8)\n        for path in x.BASE_PINS:\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = (c.ROOT / x.DISPATCHER).read_bytes()\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n"),
        (b"                    self.assertEqual(x.normalize(path, prior), prior)\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = staging_bytes(path, (c.ROOT / path).read_bytes())\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n", b"                    self.assertEqual(x.normalize(path, prior), prior)\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = (c.ROOT / path).read_bytes()\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n"),
        (b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse(staging_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes()).decode())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n    def test_original1304_strict303_consumer452_ids_and_bodies_are_preserved(self):\n        original = [item for group in lc.GROUPS for item in lc.inventory(group)] + lc.ids(y.CLASS) + old_cases.inventory() + previous_cases.inventory() + final_cases.inventory()\n", b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse((c.ROOT / x.PROFILE).read_text())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n    def test_original1304_strict303_consumer452_ids_and_bodies_are_preserved(self):\n        original = [item for group in lc.GROUPS for item in lc.inventory(group)] + lc.ids(y.CLASS) + old_cases.inventory() + previous_cases.inventory() + final_cases.inventory()\n"),
        (b"        changed = set()\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = staging_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            before, after = methods(frozen), methods(current)\n            self.assertEqual(before.keys(), after.keys(), path)\n", b"        changed = set()\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            before, after = methods(frozen), methods(current)\n            self.assertEqual(before.keys(), after.keys(), path)\n"),
        (b'        for path in (\'scripts/rc_consumer_default_worker_proof.py\', \'scripts/rc_consumer_default_worker_proof_tests.py\',\n                \'scripts/rc_consumer_transport_worker.py\', \'scripts/rc_consumer_c_93c2ad95_io.txt\'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path))\n        text = staging_bytes(x.WORKFLOW, (c.ROOT / x.WORKFLOW).read_bytes()).decode()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n', b'        for path in (\'scripts/rc_consumer_default_worker_proof.py\', \'scripts/rc_consumer_default_worker_proof_tests.py\',\n                \'scripts/rc_consumer_transport_worker.py\', \'scripts/rc_consumer_c_93c2ad95_io.txt\'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path))\n        text = (c.ROOT / x.WORKFLOW).read_text()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n'),
        (b"        self.assertTrue(all(not (c.ROOT / path).exists() and not (c.ROOT / path).is_symlink() for path in held))\n        for path in ('scripts/rc_release_eligibility.py', 'scripts/rc_publication_contract.py', 'scripts/rc_publication_stage.py',\n                'scripts/rc_consumer_io.py', 'scripts/rc_artifact_consumer.py', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual(staging_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n    def test_new24_inventory_and_exceptional_outcomes_reject(self):\n        loaded = inventory()\n", b"        self.assertTrue(all(not (c.ROOT / path).exists() and not (c.ROOT / path).is_symlink() for path in held))\n        for path in ('scripts/rc_release_eligibility.py', 'scripts/rc_publication_contract.py', 'scripts/rc_publication_stage.py',\n                'scripts/rc_consumer_io.py', 'scripts/rc_artifact_consumer.py', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n    def test_new24_inventory_and_exceptional_outcomes_reject(self):\n        loaded = inventory()\n"),
    ),
    '.github/workflows/issue88-publication-executor.yml': (
        (b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen one hundred sixty-eight cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n", b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen one hundred forty-four cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n"),
        (b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_staging_budget_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              import rc_pretag_download_budget_cases as download_budget\n              import rc_pretag_staging_budget_cases as staging_budget\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n", b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_download_budget_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              import rc_pretag_download_budget_cases as download_budget\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n"),
        (b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'download-budget-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert download_budget.execution_valid(loaded, result)\n              names = staging_budget.inventory()\n              suite = unittest.defaultTestLoader.loadTestsFromNames(names)\n              loaded = [test.id() for test in c._flatten(suite)]\n              with (evidence / 'staging-budget-cases.log').open('w', encoding='utf-8') as output:\n                  result = unittest.TextTestRunner(stream=output, verbosity=2, resultclass=c.InventoryResult).run(suite)\n              receipt = {'loaded_ids': loaded, 'executed_ids': result.executed_ids, 'tests_run': result.testsRun,\n                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'staging-budget-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert staging_budget.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n", b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'download-budget-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert download_budget.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n"),
    ),
}
# END SEALED SOURCE
DISPATCH = (
    b'    import rc_pretag_staging_budget_profile as staging\n'
    b'    selected = staging.select(ref, root, git, entries, historical, release, release_tree, documents)\n'
    b'    if selected is not None:\n'
    b'        return selected\n'
)
NORMALIZE = (
    b'    from rc_pretag_staging_budget_profile import normalize as staging_bytes\n'
    b'    current = staging_bytes(path, current)\n'
)
NEW_CASES = {
    'rc_publication_staging_budget_cases.StagingBudgetCases': ('test_default_stage_and_consumer_keep_download_defaults', 'test_session_shares_activation_deadline_and_bound_callback', 'test_receipt_timeout_reaps_child_and_never_starts_final', 'test_receipt_cancellation_reaps_child_and_never_starts_final', 'test_final_timeout_reaps_both_children', 'test_final_cancellation_reaps_both_children', 'test_deadline_expiring_between_downloads_prevents_second_launch', 'test_cancellation_between_downloads_prevents_second_launch', 'test_transport_cleanup_uncertainty_stays_sticky_on_both_downloads', 'test_stage_cleanup_failure_overrides_timeout_and_cancel', 'test_transport_uncertainty_survives_secondary_stage_close_failure', 'test_failure_mapping_is_closed_and_activation_cleanup_is_one_shot'),
    'rc_pretag_staging_budget_cases.StagingBudgetCompositionCases': ('test_exact_m_identity_and_fresh_historical_validation', 'test_ordered_d_i_j_and_exact_four_document_overlay', 'test_wrong_repeated_nested_correction_and_same_tree_parents_reject', 'test_all_thirteen_paths_modes_pins_and_entry_counts_are_exact', 'test_individual_and_total_budgets_fail_closed', 'test_exact_dispatch_and_seven_inverses_recover_complete_m_bytes', 'test_missing_duplicate_outside_and_binary_inverse_edits_reject', 'test_selected_historical_and_release_content_errors_are_terminal', 'test_actual_candidate_validation_is_never_cached', 'test_original1328_strict303_consumer452_ids_and_bodies_are_preserved', 'test_readonly_workflow_and_held_sources_remain_bounded', 'test_new24_inventory_and_exceptional_outcomes_reject'),
}
CLASS = 'rc_pretag_staging_budget_cases.StagingBudgetCompositionCases'
NAMES = NEW_CASES[CLASS]
DIGEST = '7cc2384daefdd36a16c9d8804d968735de46a1ef5b73c8f050c70b850ee6e105'


def normalize(path, current):
    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""
    assert type(path) is str and type(current) is bytes, 'staging inverse input'
    if path not in BASE_PINS:
        return current
    identity = o.pin(current)
    baseline = BASE_PINS[path]
    if identity == baseline[1:3] or identity in PRIOR_PINS.get(path, ()):
        return current
    row = SOURCE_PINS[path]
    assert (identity, len(current), len(current.splitlines())) == (row[1:3], row[3], row[4]), path
    restored = current
    for before, after in reversed(FRAGMENTS[path]):
        assert before and restored.count(before) == 1, 'staging fragment missing or duplicated'
        restored = restored.replace(before, after, 1)
    assert (o.pin(restored), len(restored), len(restored.splitlines())) == (
        baseline[1:3], baseline[3], baseline[4]), 'complete staging M inverse'
    return restored


def topology(ref, root, git, release):
    """Only D[M], I[M,D], J[R,I]; no correction chains or ancestry inference."""
    if release != p.R:
        raise o.TopologyError('staging_release_anchor')
    parents = o._parents(ref, root, git)
    if parents == [M]:
        kind, tip, source = 'nonrelease', ref, ref
    elif len(parents) == 2 and parents[0] == M:
        kind, tip, source = 'nonrelease', ref, parents[1]
    elif len(parents) == 2 and parents[0] == p.R:
        kind, tip = 'release', parents[1]
        feature_parents = o._parents(tip, root, git)
        if len(feature_parents) != 2 or feature_parents[0] != M:
            raise o.TopologyError('staging_feature_parents')
        source = feature_parents[1]
    else:
        raise o.TopologyError('staging_candidate_parents')
    if o._parents(source, root, git) != [M]:
        raise o.TopologyError('staging_candidate_parent')
    return kind, tip, source


def content(ref, root, git, entries, historical, release, release_tree, documents):
    """Fresh immutable M admission, exact candidate pins and complete reviewed delta."""
    assert (release, release_tree, documents) == (p.R, p.R_TREE, p.R_DOCUMENTS)
    assert tuple(o._parents(M, root, git)) == M_PARENTS, 'staging M parents'
    assert git('rev-parse', M + '^{tree}', root=root).decode().strip() == M_TREE, 'staging M tree'
    baseline = p.selected_profile(M, root, git, entries, historical, release, release_tree, documents)
    assert baseline == entries(M, root) and len(baseline) == 1764
    actual, paths = entries(ref, root), CAPS.keys()
    assert len(paths) == 13 and SOURCE_PINS.keys() == paths - {PROFILE}
    assert baseline.keys() & paths == BASE_PINS.keys() and len(BASE_PINS) == 7
    assert FRAGMENTS.keys() == BASE_PINS.keys() and PRIOR_PINS.keys() <= BASE_PINS.keys()
    assert len(PRIOR_PINS) == 3 and sum(map(len, PRIOR_PINS.values())) == 12
    assert actual.keys() == baseline.keys() | paths and len(actual) == 1770
    assert {path for path in actual if actual[path] != baseline.get(path)} == paths
    assert all(actual[path] == value for path, value in baseline.items() if path not in paths)
    assert all(actual[path][:2] == ('100644', 'blob') for path in paths)
    assert all(actual[path] == (row[0], 'blob', row[1]) for path, row in SOURCE_PINS.items())
    data = {path: git('cat-file', 'blob', actual[path][2], root=root) for path in paths}
    for path, (mode, blob, digest, size, count) in SOURCE_PINS.items():
        assert mode == '100644' and o.pin(data[path]) == (blob, digest), path
        assert (len(data[path]), len(data[path].splitlines())) == (size, count), path
    for path, row in BASE_PINS.items():
        assert baseline[path] == (row[0], 'blob', row[1]), path
        assert normalize(path, data[path]) == git('cat-file', 'blob', baseline[path][2], root=root), path
    p.authenticated._budgets(ref, M, root, git, data, CAPS, DELTA_LIMIT, 'staging_delta_budget')
    return actual


def select(ref, root, git, entries, historical, release, release_tree, documents):
    """Only topology mismatch delegates; selected and historical content errors escape."""
    ref = o._commit(ref, root, git)
    try:
        kind, tip, source = topology(ref, root, git, release)
    except o.TopologyError:
        return None
    expected = content(source, root, git, entries, historical, release, release_tree, documents)
    assert entries(tip, root) == expected
    if kind == 'release':
        return o.release_content(ref, expected, root, git, entries, release, release_tree, documents)
    return expected
