"""Finite integration admission source; independent full-tree review binds this module."""
import rc_pretag_ownership_profile as o
import rc_pretag_publication_profile as p

B = 'c2b5afb2c46318e2c54283f8442d5996e55f0a73'
B_TREE = '428da2c6345e99d847094755098af08967578cca'
B_PARENTS = ('5beda478f4d04e7a352d0bbc63e1496ee3bca668', '9525dd6cae2c9b8a7fefeb31c71f12b1e05b397f')
PROFILE = 'scripts/rc_pretag_integration_admission_profile.py'
CASES = 'scripts/rc_pretag_integration_admission_cases.py'
DISPATCHER = 'scripts/rc_pretag_publisher_executor_profile.py'
WORKFLOW = '.github/workflows/issue88-publication-executor.yml'
CAPS = {
    'scripts/rc_publication_admission.py': (240, 240),
    'scripts/rc_publication_admission_cases.py': (480, 480),
    'scripts/rc_pretag_integration_admission_profile.py': (400, 400),
    'scripts/rc_pretag_integration_admission_cases.py': (400, 400),
    'docs/specs/issue88-integration-admission/requirements.md': (40, 40),
    'docs/specs/issue88-integration-admission/design.md': (80, 80),
    'docs/specs/issue88-integration-admission/tasks.md': (60, 60),
    'scripts/rc_release_policy.py': (180, 35),
    'scripts/rc_publication_github.py': (500, 55),
    'scripts/rc_publication_executor.py': (255, 30),
    'scripts/rc_publication_https_fixture.py': (220, 8),
    'scripts/rc_publication_github_cases.py': (370, 4),
    'scripts/rc_pretag_policy_tests.py': (255, 6),
    'scripts/rc_pretag_publisher_executor_profile.py': (190, 4),
    'scripts/rc_pretag_publisher_executor_cases.py': (330, 55),
    'scripts/rc_pretag_composition_tests.py': (493, 8),
    'scripts/rc_pretag_join_once_tests.py': (500, 6),
    'scripts/rc_pretag_snapshot_warning_cases.py': (450, 12),
    'scripts/rc_pretag_appimage_cases.py': (410, 14),
    'scripts/rc_pretag_linux_package_cases.py': (470, 48),
    'scripts/rc_pretag_yoke_repair_cases.py': (302, 28),
    'scripts/rc_pretag_publication_adapters.py': (256, 12),
    'scripts/rc_pretag_linux_package_inverse.py': (178, 8),
    'scripts/rc_pretag_appimage_profile.py': (157, 4),
    '.github/workflows/issue88-publication-executor.yml': (90, 35),
    'scripts/rc_publication_executor_cases.py': (350, 60),
}
DELTA_LIMIT = 2300
BASE_PINS = {
    'scripts/rc_release_policy.py': ('100644', '58b8aa42255c440ee5bdbe46fe67965e5acb1724', 'f63705d96312f1d1b4dd31394ad6c4d450748ce7a65fbb3c90c6b676d0755c9f', 12591, 156),
    'scripts/rc_publication_github.py': ('100644', 'b4d250974e89deeb241f2aa32a998cda17688e34', '62fbe64ffc69c15d0def289f13ff282ed4046fee05a584b20b228f92488f1d90', 23025, 474),
    'scripts/rc_publication_executor.py': ('100644', 'a64cf4c91ad43c0efd35e0a5c8c0d1de96cdfd11', 'e13ceb317de92c724cecafac06875659f0eacd8e66aa2a76c964fdded176a02e', 9819, 235),
    'scripts/rc_publication_https_fixture.py': ('100644', '685c97f89de9fb5c565999c700c306c5376b7442', '24076b28befe41350f86a340f98f058325b6d1df31b83db0fcf3f1c55970b81e', 10537, 214),
    'scripts/rc_publication_github_cases.py': ('100644', '1097fd0309671110156bfff25b3ffbd3732edb80', '923f429222a581de256501c86e1b0516a541ca5cde839895e2dbee6436bd7732', 22455, 363),
    'scripts/rc_pretag_policy_tests.py': ('100644', '004133bd73c7ebfa243d79ba42a4565e7b945cd5', 'b78d9f65a1256b8ff819f0b2a7832302e835f429cb8d4c0bac9b1a3728a4c5b0', 15004, 250),
    'scripts/rc_pretag_publisher_executor_profile.py': ('100644', 'e389063643ed760a2ab2282eb80881a2bf5610ed', '63c3dcd83cda37b821906088b8ee7ace360479b76651797428dc176a4f523938', 11928, 186),
    'scripts/rc_pretag_publisher_executor_cases.py': ('100644', '8f95924dd66b6f416e10d6b7ab8f197dbe336358', 'd5c1b8283fc9914da3209e13c09ff9a946fff311baab39672715f6fc7d83b750', 20119, 300),
    'scripts/rc_pretag_composition_tests.py': ('100644', '56549d0a55f3162dfb7b3ed993e4ddcff18ff69f', '105f8562da48ff4557898e017ead8762f55e55357a664e1372e1443d25f217e2', 36290, 489),
    'scripts/rc_pretag_join_once_tests.py': ('100644', '12d613675c60dc5babbcfa4324691b583896e943', '52e4276c4a25531c62ed34d5715e778dc091be12d91cb84cbae0b229a272ea1b', 33738, 497),
    'scripts/rc_pretag_snapshot_warning_cases.py': ('100644', 'dcd96b0a4d3b0375a60df3017986b375550ae88e', 'f61985704f42232a5436075d4cf57ee14c311a5957491c45894c969984474713', 29679, 446),
    'scripts/rc_pretag_appimage_cases.py': ('100644', 'be5464078eb8369452ae28e94d4baa9f446746e0', 'a9fc69726fac6188b6a0650b222bc4b4bb66c22618918d71f88cde426cd2b6eb', 29783, 402),
    'scripts/rc_pretag_linux_package_cases.py': ('100644', '2e8b789a708ff1b6d9bcbe71a083696c075e0eb4', '94c6c06f480c99f958bd316ae4c985a6182f37851f89408024d97147e3a13168', 30386, 440),
    'scripts/rc_pretag_yoke_repair_cases.py': ('100644', '7d56da99888ecb3e42bc0e42c687805c9ec21bcf', '97e9aae15068d2827c96101c4a0143173e8db3eb9d7adbc43cf88ab137b46646', 18358, 286),
    'scripts/rc_pretag_publication_adapters.py': ('100644', 'a7b2fa2675551c0d6156192e57266d697cbbf544', '88b4a1452a9f4b050e1f7d7767eb202b07dab3d5bce17c275a60e3e0fd9ae329', 24677, 248),
    'scripts/rc_pretag_linux_package_inverse.py': ('100644', 'fe6f6ab0362d1005e3e3a41f573504574118b6af', '22e91e1c47d803dcc2cd002cdea81b9dbf32ef0d358e490038243fd5cb6c45a0', 109917, 172),
    'scripts/rc_pretag_appimage_profile.py': ('100644', '1903473701ad2e8780e7db812f98c7e3d26b7c75', 'e319be4c77e392e1bfc78938e91af1e98684cb710dbe3d6393a22ed200cc8286', 10957, 153),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'c6cc466d9d2520b668508e6fbd9754f1ac1cc7ef', '850aea3f1d81c00322f8c8ca1adf84a5abddb5c75d916066394f41a521397e4e', 4677, 69),
    'scripts/rc_publication_executor_cases.py': ('100644', '9b3c84e25470a775329a8bb49704b329409a0576', '32d11ddd521fd9a0a4a947b1d5fb506d1a1dd955a45734afda2cf53a40e1e5fc', 16114, 298),
}
# BEGIN SEALED SOURCE
SOURCE_PINS = {
    'scripts/rc_publication_admission.py': ('100644', '4d4c9ab80a80c94e7cddf994af7ddc0b42bad251', '412af5d5110b590d719907e305d564769cd5796cbe24c30ea5c6a79c19db2178', 7801, 155),
    'scripts/rc_publication_admission_cases.py': ('100644', '2b4dee642d101127e00229658b720a93662b99ad', 'eb1d75cc4984804b39e22a9de5fb245384afd7e6ac507a599427fb34d449ea04', 23556, 386),
    'scripts/rc_pretag_integration_admission_cases.py': ('100644', 'd074861b9e655cbc38807bd0f38187690e4d0e3c', 'f3bb03dcbeca0a3c68a55879dbefa37f7e038cfcca774852e9f29a36f4ee480d', 22105, 345),
    'docs/specs/issue88-integration-admission/requirements.md': ('100644', '60f5de46a47c247484a8cf1d4a7bfbbacae9615d', 'b92817086f7e518ec7312072cfa6add92f3457cf755b85a109e063b5f6bcc9a9', 4209, 31),
    'docs/specs/issue88-integration-admission/design.md': ('100644', 'fda7797a0d7e80457569316bcd9867c40c362ffb', 'ae5663e5c34f6c66932f77cd73ad7494d1b1bdb409988386a6ec45c3b3714ced', 7717, 34),
    'docs/specs/issue88-integration-admission/tasks.md': ('100644', '06a7dba95b3d48e61462fbe2fc301261e7375aa3', '3086adcb55a94fd3609d480a20ba6534234850280ef505b234fd96592657ea7a', 5249, 49),
    'scripts/rc_release_policy.py': ('100644', 'a98cb286d1f963d7c8d2f984b64c5017aab4fbc1', '5a4b8c642dd8a654f423c88bff0314fba4b5e1ddfcad3579e4e9ca72d565b876', 13637, 168),
    'scripts/rc_publication_github.py': ('100644', '8acb81c087751d0e6554144f365053f2074238cb', '1944d7aa4bab79c32747f3722bd07af8f9d801ce887d9597933ffbafa0c20bb6', 23521, 482),
    'scripts/rc_publication_executor.py': ('100644', '2e22b0b14013dbac09d21a3daceb425c371c2932', '9adf8f0b43f85d276f450e194cc5bb553a67485082b9729fcc9a3b4d7d7951af', 9957, 235),
    'scripts/rc_publication_https_fixture.py': ('100644', '76e38e9e2bd020238820f7408fd490995d2b66ba', 'e18648a109e7980f426f15663a208a045eabab5c6981816d6f989635b6c81649', 10554, 214),
    'scripts/rc_publication_github_cases.py': ('100644', '8cf3a0512e50149df7590f0a5144c76d4d8637a6', '578dc3569e2cd56d60c55f440b1ca0c14e8e967e4c86da3b35af58d435452e12', 22469, 363),
    'scripts/rc_pretag_policy_tests.py': ('100644', 'bf1725b106ea55dcac2f0c70aeddece436fb2681', 'f9df6c3c9fbea03e70b50fc4f889eee3100e9556f2de6d61892a5cb87c0346ce', 15108, 251),
    'scripts/rc_pretag_publisher_executor_profile.py': ('100644', 'd8ac41ced8e737ebc7e3d01665e137aefff5cad4', '5a4babefb29b4f2baecccfa5bf0e34a473975fa22428a93317a5bb71ff8ee988', 12152, 190),
    'scripts/rc_pretag_publisher_executor_cases.py': ('100644', '8bdde562311efe7a17411be13ffa63b6d8175bc1', '36cb7372a713877b22427fa92110326154c64fd12b8a30c278acb6f67f462b57', 20484, 301),
    'scripts/rc_pretag_composition_tests.py': ('100644', '2bebb78514e8e7c8358e5bac4c2cbfb2d09ecd8b', 'b285be0f99bfa93aaa21179c8b97a248c3afbfa4c7b977fa3e52e22d041eb4ce', 36423, 490),
    'scripts/rc_pretag_join_once_tests.py': ('100644', 'a8b35ff265b1e376383e0727c5fbedda7bed3c6e', '8fdc358128830331eae79292b1b75424e2ad0ea6943bf501aada76cdeb4b23ff', 33846, 498),
    'scripts/rc_pretag_snapshot_warning_cases.py': ('100644', '1e6b0f14e727b88c97eda35bb7c8333baa6f97db', '734a1f2eecd78e8188d075f1a750c7b4705fadb60851d4ab9aad80d9fda038cf', 29874, 447),
    'scripts/rc_pretag_appimage_cases.py': ('100644', '57fc63e62a160ec62c561fd4534abb7f63140c47', '800bc7a72a72e8f1536175b615df46f0e2718e15a89006d3f1216089232d81d3', 30009, 403),
    'scripts/rc_pretag_linux_package_cases.py': ('100644', '2ea86c8f16b54dd26055426ed9366c4a0b28c889', '35ccea67a8d063d4b8134be107d633ed23fba0c3453df7a2ec2e8332fec05afd', 30783, 441),
    'scripts/rc_pretag_yoke_repair_cases.py': ('100644', '7b204373a5cd580e0bf3dd8fe29f0d3079d2e1de', '261076d2bb35d740e218ea34e865f06ec959188123d813ccf1679d18ef40383e', 18636, 287),
    'scripts/rc_pretag_publication_adapters.py': ('100644', '9600a78904440a71e807af95a1d4cc20121a0dd6', 'a1f8734d53bba966709c1cfdaa4bad11ef37c4c8f42256141540741b17502042', 24882, 251),
    'scripts/rc_pretag_linux_package_inverse.py': ('100644', '21b8094491330bd443bbd276a20292a9f22695c7', 'f9aef48bea52bbc7141f932496eecb905d960b673873fbab763badba2671ce51', 110094, 175),
    'scripts/rc_pretag_appimage_profile.py': ('100644', 'd2e331fd8e826e9ea8542665a0fc0b6fee20d89f', '7a37e92e86acaa16b253ef90a6fc6a4bccadaca47d8944bc98a018234d7ab901', 10911, 153),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'd06143c505bf739dfd4336ea97c20b5850d15128', 'ceb14dd7012995f1d3400e1eb7dfc24533b564cd9a039e2592c74b153d036634', 5636, 79),
    'scripts/rc_publication_executor_cases.py': ('100644', '0e8251b9a49af68ee1a9ff85e2d013233a5c53cb', 'a86752e0fcf69cb9ff11de39e109565f8896e071cfd783ddff56b5006311c782', 16526, 303),
}
PRIOR_PINS = {
    'scripts/rc_pretag_composition_tests.py': (('988c4be1175b68feecc2c38f8aee7f932e4589e2', 'ff5e95e6ff14416aa969e1c9dad9e729c96c3aa624da63af4ff93c9edc397694'), ('99483e8545add6209aee035b7460d5b56c023a82', 'f0cf5e2ff2739efd976125d893bf9cd58a5c1d0706a4b9cf95d998811b706488'), ('67e97761d6570869e64ea04276b635cd89f3ccc1', '5bf44aac60240fb6ee5d0af5afd82a8aa16ff4008ec78530cab937753e47a029'), ('f306ba3902577acc5f8d3b8c0537b1921050e062', '061036efcb39239f3251d3f212472166c2f5f2b1a2d37c3cc9ea0e75da8b4a4a'), ('959bddf9d5f32767e033418bb4823e8c7ef32a77', '132fb6b5760fbefdb0d728f8400d3ee8544c6218329483e5ec5828d2f6b81cf6'), ('6aceb93ede42cecac841e12d30bd35ae156ba8ef', '61098cd058653f1585ae35bcec620ab8a209535cf8b81b78dcbb47b62e88c10c'), ('00d8e657375a479779d7c06ef33cb847ff9f49d0', 'e8c1ac54d30a4030f9b843aeee1c1ff1a94013641f533f1e97e35603d25e8c74')),
    'scripts/rc_pretag_join_once_tests.py': (('a82efa478868410d257da54bf5285a6691b0f37b', '40ee7d6123d8dd14ac235923a8e972946b4e88ba51681a6d8d5aa76ed916c26a'),),
    'scripts/rc_pretag_snapshot_warning_cases.py': (('23b1669bfe2f5565fc6e13b957e6b9451e02eded', '45b4425fc45c2b46d30cd4de970c0f59d46d8bb143fd77d30497f87199e98ec4'),),
    'scripts/rc_pretag_appimage_cases.py': (('d223899eb5ce0d566ca3f86febb9a3c8492777e5', '5b6aace0b5d2237b1f650eb9072abd13dfc6341e35e83f7885ad2f48d751c248'),),
    'scripts/rc_pretag_publication_adapters.py': (('669f38760c6ea949b468d5c140a684570c009994', 'fbbea7fac1121f8b7f1aa7b1237c7633292b2e7921d15c53bc0f776913d1bad6'), ('5fe498145f77d1f73f8f1142810f2d1441ed0bcd', 'b5a822b35a105e5d7dd64997690ac9612dece7f900447aeb440d1eeb46586687')),
    'scripts/rc_pretag_appimage_profile.py': (('2787e7dd91ffe199c9421d7d6b8c0cb324998645', '33f041c22ee4870ffd30facbe2d4601cb7878dd7d4eb5513ab29983fdac64442'),),
}
FRAGMENTS = {
    'scripts/rc_release_policy.py': (
        (b'"""Fixed evidence requirements; only full_integration has a live read-only verifier."""\nfrom dataclasses import dataclass\n\n', b'"""Fixed non-executable evidence requirements; no row has a live verifier yet."""\nfrom dataclasses import dataclass\n\n'),
        (b"             ROOT + '/actions/runs/{run_id}/artifacts', ROOT + '/actions/artifacts/{artifact_id}',\n             ROOT + '/actions/artifacts/{artifact_id}/zip')\nINTEGRATION_READS = (ROOT, ROOT + '/git/ref/{selected_ref}', ROOT + '/git/commits/{source_sha}',\n    ROOT + '/git/trees/{tree_sha}', ROOT + '/actions/workflows/dot-rc-integration.yml',\n    ROOT + '/actions/workflows/{workflow_id}/runs?head_sha={source_sha}', ROOT + '/actions/runs/{run_id}',\n    ROOT + '/actions/runs/{run_id}/attempts/{run_attempt}',\n    ROOT + '/actions/runs/{run_id}/attempts/{run_attempt}/jobs')\nREVIEW_READS = (ROOT + '/pulls/36', ROOT + '/pulls/36/reviews',\n                ROOT + '/pulls/36/reviews/{review_id}', ROOT + '/pulls/36/commits')\n", b"             ROOT + '/actions/runs/{run_id}/artifacts', ROOT + '/actions/artifacts/{artifact_id}',\n             ROOT + '/actions/artifacts/{artifact_id}/zip')\nREVIEW_READS = (ROOT + '/pulls/36', ROOT + '/pulls/36/reviews',\n                ROOT + '/pulls/36/reviews/{review_id}', ROOT + '/pulls/36/commits')\n"),
        (b"            sequence(value, str, 16)\n        require(all(p in PERMISSIONS for p in self.permissions), 'invalid_policy_permission')\n        require(self.verifier == ('github_full_integration_v1' if self.gate_id == 'full_integration'\n                                  else 'unimplemented'), 'unsupported_policy_verifier')\n\n\n", b"            sequence(value, str, 16)\n        require(all(p in PERMISSIONS for p in self.permissions), 'invalid_policy_permission')\n        require(self.verifier == 'unimplemented', 'unsupported_policy_verifier')\n\n\n"),
        (b"    completeness = 'newest same-source run across all statuses; exact current-attempt jobs; bounded complete lists'\n    identity = 'repository ID/name, source SHA/tree, workflow, run/current attempt/job and API ZIP digest/size'\n    if key == 'full_integration':\n        endpoints = INTEGRATION_READS\n        visibility = 'authenticated same-repository source/workflow/run/attempt/job metadata only'\n        identity = 'repository ID/name, source SHA/tree, workflow blob/ref, newest run/current attempt and exact jobs'\n    if family == 'source':\n        endpoints, permissions = SOURCE_READS, ('contents:read',)\n", b"    completeness = 'newest same-source run across all statuses; exact current-attempt jobs; bounded complete lists'\n    identity = 'repository ID/name, source SHA/tree, workflow, run/current attempt/job and API ZIP digest/size'\n    if family == 'source':\n        endpoints, permissions = SOURCE_READS, ('contents:read',)\n"),
        (b"    return GateRequirement(key, scope, ledger, endpoints, contract, permissions, visibility, identity,\n        completeness, 'missing/denied/truncated/stale/failed/skipped/unknown => blocked; no older-green fallback',\n        ('repeat complete source/workflow/run/current attempt/job observations; non-atomic' if key == 'full_integration'\n         else 'repeat source/run/current attempt/job/artifact/visibility observations at every admission fence; non-atomic'),\n        verifier='github_full_integration_v1' if key == 'full_integration' else 'unimplemented')\n\n\n", b"    return GateRequirement(key, scope, ledger, endpoints, contract, permissions, visibility, identity,\n        completeness, 'missing/denied/truncated/stale/failed/skipped/unknown => blocked; no older-green fallback',\n        'repeat source/run/current attempt/job/artifact/visibility observations at every admission fence; non-atomic')\n\n\n"),
    ),
    'scripts/rc_publication_github.py': (
        (b"import rc_publication_contract as core\nfrom rc_consumer_io import CHUNK, FILE_LIMIT\nfrom rc_pretag_types import REPOSITORY\nimport rc_publication_admission as admission\n\nAPI, UPLOAD, STORAGE = 'api.github.com', 'uploads.github.com', 'release-assets.githubusercontent.com'\n", b"import rc_publication_contract as core\nfrom rc_consumer_io import CHUNK, FILE_LIMIT\nfrom rc_pretag_types import POLICY_REVISION, REPOSITORY\nfrom rc_release_eligibility import GateResult, ReleaseEligibility\nfrom rc_release_policy import GATES\n\nAPI, UPLOAD, STORAGE = 'api.github.com', 'uploads.github.com', 'release-assets.githubusercontent.com'\n"),
        (b"\n\ndef _authenticate(selection, api, *, check_active, deadline):\n    try:\n        report = admission.authenticate_integration(api, selection, check_active=check_active, deadline=deadline)\n    except admission._Interrupted as error:\n        raise WireFailure(error.code, 'none') from None\n    except WireFailure:\n        raise\n    except Exception:\n        raise WireFailure('verification_failed', 'none') from None\n    _need(all(row[3] == 'passed' for row in report.rows) and report.draft_visibility == 'proven', 'fence_blocked')\n    return report.rows, report.draft_visibility\n\n\n", b"\n\ndef _authenticate(selection):\n    rows = tuple(GateResult(g.gate_id, 'missing', 'unknown',\n                           'authenticating_producer_unimplemented') for g in GATES)\n    eligibility = ReleaseEligibility(selection.subject.source, POLICY_REVISION, 'blocked', rows)\n    _need(all(g.verifier == 'unimplemented' for g in GATES)\n          and eligibility.status == 'blocked' and not eligibility.release_approved, 'fence_blocked')\n    raise WireFailure('fence_blocked', 'none')\n\n\n"),
        (b"        sock = None\n        possible, confirmed, result, failure = False, False, None, None\n        deadline = time.monotonic() + DEADLINE if deadline is None else deadline\n        try:\n            _need(not self._closed, 'cancelled')\n            check_active()\n            _need(time.monotonic() < deadline, 'timeout')\n            self._closed_request(method, host, path, body, stream, asset, op)\n            _need(op is None or (not anonymous and not binary), 'invalid_request')\n", b"        sock = None\n        possible, confirmed, result, failure = False, False, None, None\n        deadline = deadline or time.monotonic() + DEADLINE\n        try:\n            _need(not self._closed, 'cancelled')\n            self._closed_request(method, host, path, body, stream, asset, op)\n            _need(op is None or (not anonymous and not binary), 'invalid_request')\n"),
        (b'            reader.check()\n            if op is not None:\n                _authenticate(self.selection, self, check_active=check_active, deadline=deadline)\n                _remote_constraint(self.selection.subject)\n                _authorize(op, self.selection.subject)\n', b'            reader.check()\n            if op is not None:\n                _authenticate(self.selection)\n                _remote_constraint(self.selection.subject)\n                _authorize(op, self.selection.subject)\n'),
        (b"              and stream is None and asset is None, 'invalid_request')\n\n    def _metadata(self, suffix, anonymous=False, deadline=None, absent=False, check_active=lambda: None):\n        status, _, body = self._request('GET', API, ROOT + ('' if suffix == '/' else suffix),\n                                       anonymous=anonymous, deadline=deadline, check_active=check_active)\n        if status == 404 and absent:\n            return None\n", b"              and stream is None and asset is None, 'invalid_request')\n\n    def _metadata(self, suffix, anonymous=False, deadline=None, absent=False):\n        status, _, body = self._request('GET', API, ROOT + ('' if suffix == '/' else suffix),\n                                       anonymous=anonymous, deadline=deadline)\n        if status == 404 and absent:\n            return None\n"),
        (b"\n    @_safe\n    def get(self, suffix, *, deadline=None, check_active=lambda: None):\n        _need(type(suffix) is str and re.fullmatch(r'/[A-Za-z0-9_./?=&-]*', suffix)\n              and '..' not in suffix and '//' not in suffix, 'invalid_request')\n        value = self._metadata(suffix, deadline=deadline, check_active=check_active)\n        check_active()\n        _need(deadline is None or time.monotonic() < deadline, 'timeout')\n        return value\n\n    def _pages(self, suffix, anonymous, deadline):\n", b"\n    @_safe\n    def get(self, suffix):\n        _need(type(suffix) is str and re.fullmatch(r'/[A-Za-z0-9_./?=&-]*', suffix)\n              and '..' not in suffix and '//' not in suffix, 'invalid_request')\n        return self._metadata(suffix)\n\n    def _pages(self, suffix, anonymous, deadline):\n"),
        (b"        if latest is None:\n            _need(expected[1] == 0)\n            proof = _authenticated_latest_absence(self.selection)\n            _need(type(proof) is _LatestAbsent and proof.repository == REPOSITORY\n                  and proof.source_sha == self.selection.subject.source.source_sha)\n            _, visibility = _authenticate(self.selection, self, check_active=lambda: None, deadline=deadline)\n            _need(visibility == 'proven')\n            projected = None\n        else:\n", b"        if latest is None:\n            _need(expected[1] == 0)\n            _, visibility = _authenticate(self.selection)\n            _need(visibility == 'proven')\n            proof = _authenticated_latest_absence(self.selection)\n            _need(type(proof) is _LatestAbsent and proof.repository == REPOSITORY\n                  and proof.source_sha == self.selection.subject.source.source_sha)\n            projected = None\n        else:\n"),
    ),
    'scripts/rc_publication_executor.py': (
        (b'        try:\n            self._check_active()\n            wire._authenticate(self._selection, self._api, check_active=self._check_active, deadline=self._deadline)\n            wire._remote_constraint(self._selection.subject)\n            self._stage = stage_selected(self._root, self._selection, self._api,\n', b'        try:\n            self._check_active()\n            wire._authenticate(self._selection)\n            wire._remote_constraint(self._selection.subject)\n            self._stage = stage_selected(self._root, self._selection, self._api,\n'),
        (b"        fields = {}\n        if op.kind in ('ObserveFence', 'ObserveDraft', 'VerifyPublished'):\n            gates, visibility = wire._authenticate(self._selection, self._api, check_active=self._check_active, deadline=self._deadline)\n            staged = self._stage.revalidate()\n            self._check_active()\n", b"        fields = {}\n        if op.kind in ('ObserveFence', 'ObserveDraft', 'VerifyPublished'):\n            gates, visibility = wire._authenticate(self._selection)\n            staged = self._stage.revalidate()\n            self._check_active()\n"),
    ),
    'scripts/rc_publication_https_fixture.py': (
        (b"\n\ndef gates(selection, *args, **kwargs):\n    return tuple((*row, 'passed') for row in core._admission(selection.subject)), 'proven'\n\n", b"\n\ndef gates(selection):\n    return tuple((*row, 'passed') for row in core._admission(selection.subject)), 'proven'\n\n"),
    ),
    'scripts/rc_publication_github_cases.py': (
        (b"                    start = len(self.fixture.requests)\n                    with patch.object(wire, '_authenticate', side_effect=gates if passed else\n                                      lambda *args, **kwargs: (_ for _ in ()).throw(wire.WireFailure('fence_blocked', 'none'))):\n                        with patch.object(wire, '_remote_constraint', side_effect=None if passed > 1 else\n                                          lambda _: (_ for _ in ()).throw(wire.WireFailure('fence_blocked', 'none'))):\n", b"                    start = len(self.fixture.requests)\n                    with patch.object(wire, '_authenticate', side_effect=gates if passed else\n                                      lambda _: (_ for _ in ()).throw(wire.WireFailure('fence_blocked', 'none'))):\n                        with patch.object(wire, '_remote_constraint', side_effect=None if passed > 1 else\n                                          lambda _: (_ for _ in ()).throw(wire.WireFailure('fence_blocked', 'none'))):\n"),
    ),
    'scripts/rc_pretag_policy_tests.py': (
        (b"            self.assertTrue(gate.visibility and gate.identity_binding and gate.completeness)\n            self.assertTrue(gate.failure_semantics and gate.freshness)\n            expected = 'github_full_integration_v1' if gate.gate_id == 'full_integration' else 'unimplemented'\n            self.assertEqual(gate.verifier, expected)\n            self.assertLessEqual(set(gate.permissions), set(PERMISSIONS))\n            self.assertTrue(all(path.startswith('GET /repos/Eswink/coding-tools-mcp') for path in gate.endpoints))\n", b"            self.assertTrue(gate.visibility and gate.identity_binding and gate.completeness)\n            self.assertTrue(gate.failure_semantics and gate.freshness)\n            self.assertEqual(gate.verifier, 'unimplemented')\n            self.assertLessEqual(set(gate.permissions), set(PERMISSIONS))\n            self.assertTrue(all(path.startswith('GET /repos/Eswink/coding-tools-mcp') for path in gate.endpoints))\n"),
    ),
    'scripts/rc_pretag_publisher_executor_profile.py': (
        (b'    """Only topology mismatch delegates; selected or historical failures are terminal."""\n    ref = o._commit(ref, root, git)\n    import rc_pretag_integration_admission_profile as integration\n    selected = integration.select(ref, root, git, entries, historical, release, release_tree, documents)\n    if selected is not None:\n        return selected\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n', b'    """Only topology mismatch delegates; selected or historical failures are terminal."""\n    ref = o._commit(ref, root, git)\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n'),
    ),
    'scripts/rc_pretag_publisher_executor_cases.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n'),
        (b"    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob(integration_bytes(path, (c.ROOT / path).read_bytes()))) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n", b"    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob((c.ROOT / path).read_bytes())) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n"),
        (b"        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        for path, row in x.SOURCE_PINS.items():\n            data = integration_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n", b"        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        for path, row in x.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n"),
        (b"        self.assertEqual(tuple(cap[1] for cap in x.CAPS.values()), expected)\n        self.assertEqual((x.DELTA_LIMIT, sum(expected), x.CAPS[x.DISPATCHER]), (3400, 3374, (160, 4)))\n        data = {path: integration_bytes(path, (c.ROOT / path).read_bytes()) for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'publisher_delta_budget')\n", b"        self.assertEqual(tuple(cap[1] for cap in x.CAPS.values()), expected)\n        self.assertEqual((x.DELTA_LIMIT, sum(expected), x.CAPS[x.DISPATCHER]), (3400, 3374, (160, 4)))\n        data = {path: (c.ROOT / path).read_bytes() for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'publisher_delta_budget')\n"),
        (b"        protected += [path for path in self.original if path.startswith('.github/workflows/')]\n        for path in protected:\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        held = {'docs/specs/rc-source-assembly-engineering/' + name for name in ('README.md', 'design.md', 'requirements.md', 'tasks.md', 'subspecs/focused-validation/spec.md', 'subspecs/source-evidence/spec.md')}\n        held |= {'scripts/rc_source_assembly.py', 'scripts/rc_source_assembly_dispatch_tests.py', 'scripts/rc_source_assembly_tests.py', 'tests/delivery/test_linux_lifecycle_wiring.py'}\n", b"        protected += [path for path in self.original if path.startswith('.github/workflows/')]\n        for path in protected:\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        held = {'docs/specs/rc-source-assembly-engineering/' + name for name in ('README.md', 'design.md', 'requirements.md', 'tasks.md', 'subspecs/focused-validation/spec.md', 'subspecs/source-evidence/spec.md')}\n        held |= {'scripts/rc_source_assembly.py', 'scripts/rc_source_assembly_dispatch_tests.py', 'scripts/rc_source_assembly_tests.py', 'tests/delivery/test_linux_lifecycle_wiring.py'}\n"),
        (b'\n    def test_readonly_workflow_and_live_activation_boundaries(self):\n        text = integration_bytes(x.WORKFLOW, (c.ROOT / x.WORKFLOW).read_bytes()).decode()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n', b'\n    def test_readonly_workflow_and_live_activation_boundaries(self):\n        text = (c.ROOT / x.WORKFLOW).read_text()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n'),
        (b'            self.assertNotIn(forbidden, text)\n        for path in (\'scripts/rc_release_policy.py\', \'scripts/rc_release_eligibility.py\', \'scripts/rc_publication_contract.py\'):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path))\n        self.assertIn("self.verifier == \'unimplemented\'", integration_bytes(\'scripts/rc_release_policy.py\', (c.ROOT / \'scripts/rc_release_policy.py\').read_bytes()).decode())\n\n    def test_original1184_and_strict303_inventories_unchanged(self):\n', b'            self.assertNotIn(forbidden, text)\n        for path in (\'scripts/rc_release_policy.py\', \'scripts/rc_release_eligibility.py\', \'scripts/rc_publication_contract.py\'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path))\n        self.assertIn("self.verifier == \'unimplemented\'", (c.ROOT / \'scripts/rc_release_policy.py\').read_text())\n\n    def test_original1184_and_strict303_inventories_unchanged(self):\n'),
        (b"        self.assertEqual(len(set(original)), 1184)\n        for module in {item.split('.', 1)[0] for item in original}:\n            self.assertEqual(integration_bytes('scripts' + '/' + (module + '.py'), (c.ROOT / 'scripts' / (module + '.py')).read_bytes()), self.frozen('scripts/' + module + '.py'), module)\n        strict = [test.id() for test in c._flatten(unittest.defaultTestLoader.discover(str(c.ROOT / 'scripts'), pattern='rc_pretag*_tests.py'))]\n        pt.inventory_ids(strict, 303, '0ecc366c2018a6a1e20d3f59ed9ca66645d9334324cd517682894cabde923125')\n", b"        self.assertEqual(len(set(original)), 1184)\n        for module in {item.split('.', 1)[0] for item in original}:\n            self.assertEqual((c.ROOT / 'scripts' / (module + '.py')).read_bytes(), self.frozen('scripts/' + module + '.py'), module)\n        strict = [test.id() for test in c._flatten(unittest.defaultTestLoader.discover(str(c.ROOT / 'scripts'), pattern='rc_pretag*_tests.py'))]\n        pt.inventory_ids(strict, 303, '0ecc366c2018a6a1e20d3f59ed9ca66645d9334324cd517682894cabde923125')\n"),
    ),
    'scripts/rc_pretag_composition_tests.py': (
        (b'from rc_consumer_io import read_bytes\nimport rc_pretag_ownership_profile as ownership\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_desktop_profile as desktop\nimport rc_pretag_nginx_profile as nginx\n', b'from rc_consumer_io import read_bytes\nimport rc_pretag_ownership_profile as ownership\nimport rc_pretag_desktop_profile as desktop\nimport rc_pretag_nginx_profile as nginx\n'),
        (b'    def test_adopted_contracts_are_byte_identical(self):\n        for path, (blob, sha256) in ADOPTED.items():\n            data = integration_bytes(path, (ROOT / path).read_bytes())\n            if path in publication.TIMEOUT_BASE_PINS: data = publication.timeout_inverse(path, data)\n            self.assertEqual((_blob(data), hashlib.sha256(data).hexdigest()), (blob, sha256), path)\n        self.assertEqual(sum(len(integration_bytes(path, (ROOT / path).read_bytes()).splitlines()) for path in ADOPTED), 1436)\n\n    def test_snapshot_inverse_reconstructs_pinned_j(self):\n', b'    def test_adopted_contracts_are_byte_identical(self):\n        for path, (blob, sha256) in ADOPTED.items():\n            data = (ROOT / path).read_bytes()\n            if path in publication.TIMEOUT_BASE_PINS: data = publication.timeout_inverse(path, data)\n            self.assertEqual((_blob(data), hashlib.sha256(data).hexdigest()), (blob, sha256), path)\n        self.assertEqual(sum(len((ROOT / path).read_bytes().splitlines()) for path in ADOPTED), 1436)\n\n    def test_snapshot_inverse_reconstructs_pinned_j(self):\n'),
    ),
    'scripts/rc_pretag_join_once_tests.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_authenticated_two_hop_tests as at\nimport rc_pretag_publication_profile as p\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_authenticated_two_hop_tests as at\nimport rc_pretag_publication_profile as p\n'),
        (b"                              'src-tauri/Cargo.lock', 'src-tauri/tauri.conf.json', 'scripts/rc_release_policy.py',\n                              'scripts/rc_release_eligibility.py', '.github/workflows/rc-pretag-evidence.yml'}:\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        # Reuse the frozen module inventory and its exact old452 digest without executing it here.\n        tree = ast.parse(self.frozen(p.TESTS))\n", b"                              'src-tauri/Cargo.lock', 'src-tauri/tauri.conf.json', 'scripts/rc_release_policy.py',\n                              'scripts/rc_release_eligibility.py', '.github/workflows/rc-pretag-evidence.yml'}:\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        # Reuse the frozen module inventory and its exact old452 digest without executing it here.\n        tree = ast.parse(self.frozen(p.TESTS))\n"),
    ),
    'scripts/rc_pretag_snapshot_warning_cases.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_adapters as adapters\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_adapters as adapters\n'),
        (b"                     'scripts/rc_pretag_ownership_profile.py', p.authenticated.PROFILE, 'scripts/rc_pretag_two_hop_profile.py',\n                     'scripts/rc_pretag_desktop_profile.py', 'scripts/rc_pretag_nginx_profile.py'):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        for ref in (p.desktop.X, p.nginx.F, p.two_hop.F, p.authenticated.M, p.N, p.JOIN_ONCE_M, p.WARNING_B):\n            self.assertEqual(self.selected(ref), c._entries(ref, self.repo))\n        frozen = ast.parse(self.frozen(JOIN_TESTS))\n        restored = ast.parse(adapters.inverse_warning_adapter(JOIN_TESTS, integration_bytes(JOIN_TESTS, (c.ROOT / JOIN_TESTS).read_bytes())))\n        self.assertEqual(ast.dump(frozen), ast.dump(restored))\n        methods = lambda tree: {node.name: node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)}\n        old, new = methods(frozen), methods(ast.parse(integration_bytes(JOIN_TESTS, (c.ROOT / JOIN_TESTS).read_bytes())))\n        self.assertEqual(old.keys(), new.keys())\n        self.assertEqual(sum(name.startswith('test_') for name in old), 20)\n", b"                     'scripts/rc_pretag_ownership_profile.py', p.authenticated.PROFILE, 'scripts/rc_pretag_two_hop_profile.py',\n                     'scripts/rc_pretag_desktop_profile.py', 'scripts/rc_pretag_nginx_profile.py'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        for ref in (p.desktop.X, p.nginx.F, p.two_hop.F, p.authenticated.M, p.N, p.JOIN_ONCE_M, p.WARNING_B):\n            self.assertEqual(self.selected(ref), c._entries(ref, self.repo))\n        frozen = ast.parse(self.frozen(JOIN_TESTS))\n        restored = ast.parse(adapters.inverse_warning_adapter(JOIN_TESTS, (c.ROOT / JOIN_TESTS).read_bytes()))\n        self.assertEqual(ast.dump(frozen), ast.dump(restored))\n        methods = lambda tree: {node.name: node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)}\n        old, new = methods(frozen), methods(ast.parse((c.ROOT / JOIN_TESTS).read_bytes()))\n        self.assertEqual(old.keys(), new.keys())\n        self.assertEqual(sum(name.startswith('test_') for name in old), 20)\n"),
        (b"                     p.CHECKS, p.CONTRACTS, '.github/workflows/rc-pretag-evidence.yml', '.github/workflows/final-rc-packages.yml',\n                     'scripts/rc_release_policy.py', 'scripts/rc_release_eligibility.py'):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n\n\n", b"                     p.CHECKS, p.CONTRACTS, '.github/workflows/rc-pretag-evidence.yml', '.github/workflows/final-rc-packages.yml',\n                     'scripts/rc_release_policy.py', 'scripts/rc_release_eligibility.py'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n\n\n"),
    ),
    'scripts/rc_pretag_appimage_cases.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_adapters as adapters\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_adapters as adapters\n'),
        (b"        self.assertEqual(a.BASE_PINS.keys(), {p.PROFILE, p.JOIN_ONCE_HELPER, a.WARNING})\n        for path in a.BASE_PINS:\n            current = normalize(path, integration_bytes(path, (c.ROOT / path).read_bytes()))\n            frozen = self.frozen(path)\n            self.assertEqual(a.inverse_appimage_adapter(path, current), frozen)\n            self.assertEqual(a.inverse_appimage_adapter(path, frozen), frozen)\n            self.assertEqual(o.pin(frozen), a.BASE_PINS[path])\n        self.assertEqual(adapters.inverse_warning_adapter(p.PROFILE, normalize(p.PROFILE, integration_bytes(p.PROFILE, (c.ROOT / p.PROFILE).read_bytes()))),\n                         c._git('show', p.WARNING_B + ':' + p.PROFILE, root=self.repo))\n        self.assertEqual(integration_bytes(p.JOIN_ONCE_TESTS, (c.ROOT / p.JOIN_ONCE_TESTS).read_bytes()), self.frozen(p.JOIN_ONCE_TESTS))\n\n    def test_adapter_fragments_missing_duplicate_outside_edits_reject(self):\n", b"        self.assertEqual(a.BASE_PINS.keys(), {p.PROFILE, p.JOIN_ONCE_HELPER, a.WARNING})\n        for path in a.BASE_PINS:\n            current = normalize(path, (c.ROOT / path).read_bytes())\n            frozen = self.frozen(path)\n            self.assertEqual(a.inverse_appimage_adapter(path, current), frozen)\n            self.assertEqual(a.inverse_appimage_adapter(path, frozen), frozen)\n            self.assertEqual(o.pin(frozen), a.BASE_PINS[path])\n        self.assertEqual(adapters.inverse_warning_adapter(p.PROFILE, normalize(p.PROFILE, (c.ROOT / p.PROFILE).read_bytes())),\n                         c._git('show', p.WARNING_B + ':' + p.PROFILE, root=self.repo))\n        self.assertEqual((c.ROOT / p.JOIN_ONCE_TESTS).read_bytes(), self.frozen(p.JOIN_ONCE_TESTS))\n\n    def test_adapter_fragments_missing_duplicate_outside_edits_reject(self):\n"),
        (b"        for module in modules:\n            path = 'scripts/' + module + '.py'\n            current, frozen = integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            self.assertEqual(a.inverse_appimage_adapter(path, current), frozen, path)\n            methods = lambda data: {node.name: node for node in ast.walk(ast.parse(data)) if isinstance(node, ast.FunctionDef)}\n", b"        for module in modules:\n            path = 'scripts/' + module + '.py'\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            self.assertEqual(a.inverse_appimage_adapter(path, current), frozen, path)\n            methods = lambda data: {node.name: node for node in ast.walk(ast.parse(data)) if isinstance(node, ast.FunctionDef)}\n"),
        (b"        for path in ('scripts/rc_pretag_ownership_profile.py', 'scripts/rc_pretag_desktop_profile.py',\n                     'scripts/rc_pretag_nginx_profile.py', 'scripts/rc_pretag_two_hop_profile.py', p.authenticated.PROFILE):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertEqual(p.PROFILE_ID, 'engineering/issue88-publication-core-composition-v1')\n\n", b"        for path in ('scripts/rc_pretag_ownership_profile.py', 'scripts/rc_pretag_desktop_profile.py',\n                     'scripts/rc_pretag_nginx_profile.py', 'scripts/rc_pretag_two_hop_profile.py', p.authenticated.PROFILE):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        self.assertEqual(p.PROFILE_ID, 'engineering/issue88-publication-core-composition-v1')\n\n"),
    ),
    'scripts/rc_pretag_linux_package_cases.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n'),
        (b"    def setUp(self):\n        self.original = c._entries(l.M, self.repo)\n        self.good = self.original | {path: (l.MODES[path], 'blob', self.blob(integration_bytes(path, (c.ROOT / path).read_bytes()))) for path in l.CAPS}\n        self.pure = self.commit([l.M], self.good)\n        self.feature = self.commit([l.M, self.pure], self.good)\n", b"    def setUp(self):\n        self.original = c._entries(l.M, self.repo)\n        self.good = self.original | {path: (l.MODES[path], 'blob', self.blob((c.ROOT / path).read_bytes())) for path in l.CAPS}\n        self.pure = self.commit([l.M], self.good)\n        self.feature = self.commit([l.M, self.pure], self.good)\n"),
        (b"        self.assertEqual((len(l.CAPS.keys() - self.original.keys()), len(inverse.BASE_PINS)), (21, 16))\n        for path, row in l.SOURCE_PINS.items():\n            data = integration_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, (l.MODES[path], *o.pin(data), len(data), len(data.splitlines())))\n            self.assertEqual(bool((c.ROOT / path).stat().st_mode & 0o111), row[0] == '100755', path)\n", b"        self.assertEqual((len(l.CAPS.keys() - self.original.keys()), len(inverse.BASE_PINS)), (21, 16))\n        for path, row in l.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, (l.MODES[path], *o.pin(data), len(data), len(data.splitlines())))\n            self.assertEqual(bool((c.ROOT / path).stat().st_mode & 0o111), row[0] == '100755', path)\n"),
        (b"                with self.subTest(path=path, field=index), patch.dict(l.SOURCE_PINS, {path: tuple(changed)}), self.assertRaises(AssertionError):\n                    self.content()\n            self.bad_content(self.changed(path, integration_bytes(path, (c.ROOT / path).read_bytes()) + b'\\n'))\n        for pins in ({k: v for k, v in l.SOURCE_PINS.items() if k != l.CASES}, l.SOURCE_PINS | {'extra': row}):\n            with patch.dict(l.SOURCE_PINS, pins, clear=True), self.assertRaises(AssertionError):\n", b"                with self.subTest(path=path, field=index), patch.dict(l.SOURCE_PINS, {path: tuple(changed)}), self.assertRaises(AssertionError):\n                    self.content()\n            self.bad_content(self.changed(path, (c.ROOT / path).read_bytes() + b'\\n'))\n        for pins in ({k: v for k, v in l.SOURCE_PINS.items() if k != l.CASES}, l.SOURCE_PINS | {'extra': row}):\n            with patch.dict(l.SOURCE_PINS, pins, clear=True), self.assertRaises(AssertionError):\n"),
        (b"    def test_individual_and_aggregate_budgets_reject(self):\n        self.assertEqual((l.DELTA_LIMIT, sum(cap[1] for cap in l.CAPS.values())), (8500, 9161))\n        data = {path: integration_bytes(path, (c.ROOT / path).read_bytes()) for path in l.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, l.M, self.repo, git, data, l.CAPS, l.DELTA_LIMIT, 'linux_package_delta_budget')\n        budgets()\n        for path, (_, delta) in l.CAPS.items():\n            lines = len(integration_bytes(path, (c.ROOT / path).read_bytes()).splitlines())\n            with patch.dict(l.CAPS, {path: (lines - 1, delta)}), self.assertRaises(AssertionError):\n                budgets()\n", b"    def test_individual_and_aggregate_budgets_reject(self):\n        self.assertEqual((l.DELTA_LIMIT, sum(cap[1] for cap in l.CAPS.values())), (8500, 9161))\n        data = {path: (c.ROOT / path).read_bytes() for path in l.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, l.M, self.repo, git, data, l.CAPS, l.DELTA_LIMIT, 'linux_package_delta_budget')\n        budgets()\n        for path, (_, delta) in l.CAPS.items():\n            lines = len((c.ROOT / path).read_bytes().splitlines())\n            with patch.dict(l.CAPS, {path: (lines - 1, delta)}), self.assertRaises(AssertionError):\n                budgets()\n"),
        (b"        self.assertEqual(inverse.BASE_PINS.keys(), inverse.FRAGMENTS.keys())\n        for path in inverse.BASE_PINS:\n            current, frozen = integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(inverse.inverse(path, current), frozen, path)\n", b"        self.assertEqual(inverse.BASE_PINS.keys(), inverse.FRAGMENTS.keys())\n        for path in inverse.BASE_PINS:\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(inverse.inverse(path, current), frozen, path)\n"),
        (b"        for path in a.BASE_PINS:\n            frozen = c._git('show', a.M + ':' + path, root=self.repo)\n            self.assertEqual(a.inverse_appimage_adapter(path, integration_bytes(path, (c.ROOT / path).read_bytes())), frozen)\n        self.assertEqual(integration_bytes(p.JOIN_ONCE_HELPER, (c.ROOT / p.JOIN_ONCE_HELPER).read_bytes()), self.frozen(p.JOIN_ONCE_HELPER))\n\n    def test_inverse_fragments_and_historical_passthrough_pins_are_exact(self):\n", b"        for path in a.BASE_PINS:\n            frozen = c._git('show', a.M + ':' + path, root=self.repo)\n            self.assertEqual(a.inverse_appimage_adapter(path, (c.ROOT / path).read_bytes()), frozen)\n        self.assertEqual((c.ROOT / p.JOIN_ONCE_HELPER).read_bytes(), self.frozen(p.JOIN_ONCE_HELPER))\n\n    def test_inverse_fragments_and_historical_passthrough_pins_are_exact(self):\n"),
        (b'        self.assertEqual(inverse.inverse(p.PROFILE, prior), prior)\n        for path, fragments in inverse.FRAGMENTS.items():\n            current = integration_bytes(path, (c.ROOT / path).read_bytes())\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n', b'        self.assertEqual(inverse.inverse(p.PROFILE, prior), prior)\n        for path, fragments in inverse.FRAGMENTS.items():\n            current = (c.ROOT / path).read_bytes()\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n'),
        (b"        for module in {name.split('.', 1)[0] for name in old}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            self.assertEqual(inverse.normalize(path, current), frozen, path)\n            methods = lambda data: {node.name: node for node in ast.walk(ast.parse(data)) if isinstance(node, ast.FunctionDef)}\n", b"        for module in {name.split('.', 1)[0] for name in old}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            self.assertEqual(inverse.normalize(path, current), frozen, path)\n            methods = lambda data: {node.name: node for node in ast.walk(ast.parse(data)) if isinstance(node, ast.FunctionDef)}\n"),
        (b"        for path in ('scripts/rc_pretag_ownership_profile.py', 'scripts/rc_pretag_desktop_profile.py',\n                     'scripts/rc_pretag_nginx_profile.py', 'scripts/rc_pretag_two_hop_profile.py', p.authenticated.PROFILE):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertEqual(p.PROFILE_ID, 'engineering/issue88-publication-core-composition-v1')\n\n", b"        for path in ('scripts/rc_pretag_ownership_profile.py', 'scripts/rc_pretag_desktop_profile.py',\n                     'scripts/rc_pretag_nginx_profile.py', 'scripts/rc_pretag_two_hop_profile.py', p.authenticated.PROFILE):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        self.assertEqual(p.PROFILE_ID, 'engineering/issue88-publication-core-composition-v1')\n\n"),
        (b"                     '.github/workflows/windows-snapshot-warning-scope.yml', '.github/workflows/desktop-glib-backport.yml'):\n            if path in self.original:\n                self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n\n    def test_selected_content_failure_is_terminal_without_fallback(self):\n", b"                     '.github/workflows/windows-snapshot-warning-scope.yml', '.github/workflows/desktop-glib-backport.yml'):\n            if path in self.original:\n                self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n\n    def test_selected_content_failure_is_terminal_without_fallback(self):\n"),
    ),
    'scripts/rc_pretag_yoke_repair_cases.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_publication_profile as p\nimport rc_pretag_publication_tests as pt\n'),
        (b"    def setUp(self):\n        self.original = c._entries(y.F, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob(integration_bytes(path, (c.ROOT / path).read_bytes()))) for path in y.CAPS}\n        self.pure = self.commit([y.F], self.good)\n        self.feature = self.commit([y.F, self.pure], self.good)\n", b"    def setUp(self):\n        self.original = c._entries(y.F, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob((c.ROOT / path).read_bytes())) for path in y.CAPS}\n        self.pure = self.commit([y.F], self.good)\n        self.feature = self.commit([y.F, self.pure], self.good)\n"),
        (b"        self.assertEqual(y.SOURCE_PINS.keys(), y.CAPS.keys() - {y.PROFILE})\n        for path, row in y.SOURCE_PINS.items():\n            data = integration_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n", b"        self.assertEqual(y.SOURCE_PINS.keys(), y.CAPS.keys() - {y.PROFILE})\n        for path, row in y.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n"),
        (b"            'docs/specs/issue85-yoke-derive-repair/tasks.md': (40, 40), '.github/workflows/issue85-yoke-repair.yml': (145, 145),\n        })\n        data = {path: integration_bytes(path, (c.ROOT / path).read_bytes()) for path in y.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, y.F, self.repo, git, data, y.CAPS, y.DELTA_LIMIT, 'yoke_delta_budget')\n", b"            'docs/specs/issue85-yoke-derive-repair/tasks.md': (40, 40), '.github/workflows/issue85-yoke-repair.yml': (145, 145),\n        })\n        data = {path: (c.ROOT / path).read_bytes() for path in y.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, y.F, self.repo, git, data, y.CAPS, y.DELTA_LIMIT, 'yoke_delta_budget')\n"),
        (b"                     l.CASES, 'scripts/rc_pretag_linux_package_inverse.py', 'scripts/rc_release_policy.py', 'scripts/rc_release_eligibility.py',\n                     '.github/workflows/issue40-current-nginx-include.yml', 'services/local-agent/src/process.rs', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual(integration_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertNotIn('cache', integration_bytes(y.PROFILE, (c.ROOT / y.PROFILE).read_bytes()).decode())\n\n    def test_original_and_new_test_inventories_are_exact(self):\n", b"                     l.CASES, 'scripts/rc_pretag_linux_package_inverse.py', 'scripts/rc_release_policy.py', 'scripts/rc_release_eligibility.py',\n                     '.github/workflows/issue40-current-nginx-include.yml', 'services/local-agent/src/process.rs', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        self.assertNotIn('cache', (c.ROOT / y.PROFILE).read_text())\n\n    def test_original_and_new_test_inventories_are_exact(self):\n"),
        (b"        pt.inventory_ids(old, 1174, 'a40dee60873940221d23eca3b5e8af13e260f57bcbbbd72c7a77de72c93fa90a')\n        for module in {item.split('.', 1)[0] for item in old}:\n            self.assertEqual(integration_bytes('scripts' + '/' + (module + '.py'), (c.ROOT / 'scripts' / (module + '.py')).read_bytes()), self.frozen('scripts/' + module + '.py'), module)\n        strict = [test.id() for test in c._flatten(unittest.defaultTestLoader.discover(str(c.ROOT / 'scripts'), pattern='rc_pretag*_tests.py'))]\n        pt.inventory_ids(strict, 303, '0ecc366c2018a6a1e20d3f59ed9ca66645d9334324cd517682894cabde923125')\n", b"        pt.inventory_ids(old, 1174, 'a40dee60873940221d23eca3b5e8af13e260f57bcbbbd72c7a77de72c93fa90a')\n        for module in {item.split('.', 1)[0] for item in old}:\n            self.assertEqual((c.ROOT / 'scripts' / (module + '.py')).read_bytes(), self.frozen('scripts/' + module + '.py'), module)\n        strict = [test.id() for test in c._flatten(unittest.defaultTestLoader.discover(str(c.ROOT / 'scripts'), pattern='rc_pretag*_tests.py'))]\n        pt.inventory_ids(strict, 303, '0ecc366c2018a6a1e20d3f59ed9ca66645d9334324cd517682894cabde923125')\n"),
    ),
    'scripts/rc_pretag_publication_adapters.py': (
        (b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\nimport rc_pretag_authenticated_two_hop_profile as a\nimport rc_pretag_authenticated_two_hop_tests as at\n', b'import rc_pretag_composition_tests as c\nimport rc_pretag_ownership_profile as o\nimport rc_pretag_authenticated_two_hop_profile as a\nimport rc_pretag_authenticated_two_hop_tests as at\n'),
        (b'def inverse_join_once_adapter(path, current):\n    """Exact-once current inventory amendment back to the complete frozen M file."""\n    current = integration_bytes(path, current)\n    if path == p.OWNERSHIP_TESTS:\n        assert o.pin(current) == p.ANCILLARY_PINS[path]\n', b'def inverse_join_once_adapter(path, current):\n    """Exact-once current inventory amendment back to the complete frozen M file."""\n    if path == p.OWNERSHIP_TESTS:\n        assert o.pin(current) == p.ANCILLARY_PINS[path]\n'),
        (b'def publication_tests_inverse(current, adapter_source):\n    """Recover the exact removed block, four adapted methods and original wrapper."""\n    adapter_source = integration_bytes(p.JOIN_ONCE_HELPER, adapter_source)\n    assert o.pin(current) == p.JOIN_ONCE_PINS[p.TESTS][1:3]\n    assert o.pin(adapter_source) == p.JOIN_ONCE_PINS[p.JOIN_ONCE_HELPER][1:3]\n', b'def publication_tests_inverse(current, adapter_source):\n    """Recover the exact removed block, four adapted methods and original wrapper."""\n    assert o.pin(current) == p.JOIN_ONCE_PINS[p.TESTS][1:3]\n    assert o.pin(adapter_source) == p.JOIN_ONCE_PINS[p.JOIN_ONCE_HELPER][1:3]\n'),
    ),
    'scripts/rc_pretag_linux_package_inverse.py': (
        (b'"""Pure byte inverses for the finite Linux package increment."""\nimport rc_pretag_ownership_profile as o\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\n\nBASE_PINS = {\n', b'"""Pure byte inverses for the finite Linux package increment."""\nimport rc_pretag_ownership_profile as o\n\nBASE_PINS = {\n'),
        (b'    """Only exact current, complete M, and enumerated prior-valid bytes are accepted."""\n    assert type(path) is str and type(current) is bytes, \'immutable Linux package inverse input\'\n    current = integration_bytes(path, current)\n    assert path in BASE_PINS, \'unknown Linux package inverse path\'\n    pin = o.pin(current)\n', b'    """Only exact current, complete M, and enumerated prior-valid bytes are accepted."""\n    assert type(path) is str and type(current) is bytes, \'immutable Linux package inverse input\'\n    assert path in BASE_PINS, \'unknown Linux package inverse path\'\n    pin = o.pin(current)\n'),
        (b'def normalize(path, current):\n    """Normalize mapped source reads only; unrelated old source reads remain untouched."""\n    current = integration_bytes(path, current)\n    return inverse(path, current) if path in BASE_PINS else current\n', b'def normalize(path, current):\n    """Normalize mapped source reads only; unrelated old source reads remain untouched."""\n    return inverse(path, current) if path in BASE_PINS else current\n'),
    ),
    'scripts/rc_pretag_appimage_profile.py': (
        (b'    """Remove exact-once additions and recover complete immutable M bytes."""\n    import rc_pretag_linux_package_inverse as linux_package\n    current = linux_package.normalize(path, current)\n    if path not in BASE_PINS or o.pin(current) == BASE_PINS[path]:\n        return current\n', b'    """Remove exact-once additions and recover complete immutable M bytes."""\n    import rc_pretag_linux_package_inverse as linux_package\n    current = linux_package.inverse(path, current) if path in linux_package.BASE_PINS else current\n    if path not in BASE_PINS or o.pin(current) == BASE_PINS[path]:\n        return current\n'),
    ),
    '.github/workflows/issue88-publication-executor.yml': (
        (b"      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen eighty-four cases\n        shell: python\n        run: |\n", b"      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen forty-eight cases\n        shell: python\n        run: |\n"),
        (b"              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_integration_admission_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n", b"              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_publisher_executor_profile as profile\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n"),
        (b"              sha, tree = git('rev-parse', 'HEAD'), git('rev-parse', 'HEAD^{tree}')\n              parents = git('show', '-s', '--format=%P', 'HEAD').split()\n              assert sha == os.environ['GITHUB_SHA'] and parents == [profile.B]\n              expected = c.publication.selected_profile(sha, c.ROOT, c._git, c._entries, c._feature_profile, c.RELEASE, c.RELEASE_TREE, c.RELEASE_DOCS)\n              def checked():\n", b"              sha, tree = git('rev-parse', 'HEAD'), git('rev-parse', 'HEAD^{tree}')\n              parents = git('show', '-s', '--format=%P', 'HEAD').split()\n              assert sha == os.environ['GITHUB_SHA'] and parents == [profile.M]\n              expected = c.publication.selected_profile(sha, c.ROOT, c._git, c._entries, c._feature_profile, c.RELEASE, c.RELEASE_TREE, c.RELEASE_DOCS)\n              def checked():\n"),
        (b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'inventory-executed.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert x.execution_valid(loaded, result)\n              names = admission.inventory()\n              suite = unittest.defaultTestLoader.loadTestsFromNames(names)\n              loaded = [test.id() for test in c._flatten(suite)]\n              with (evidence / 'admission-cases.log').open('w', encoding='utf-8') as output:\n                  result = unittest.TextTestRunner(stream=output, verbosity=2, resultclass=c.InventoryResult).run(suite)\n              receipt = {'loaded_ids': loaded, 'executed_ids': result.executed_ids, 'tests_run': result.testsRun,\n                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'admission-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert admission.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n              (evidence / 'failure.txt').write_text(traceback.format_exc(), encoding='utf-8'); raise\n", b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'inventory-executed.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n              assert x.execution_valid(loaded, result)\n          except BaseException:\n              (evidence / 'failure.txt').write_text(traceback.format_exc(), encoding='utf-8'); raise\n"),
    ),
    'scripts/rc_publication_executor_cases.py': (
        (b"\n    def test_live_entry_is_blocked_without_real_verifiers_and_tag_guarantee(self):\n        from rc_publication_admission_cases import IntegrationTLS\n        with IntegrationTLS() as tls, tempfile.TemporaryDirectory() as root:\n            selection = tls.selection\n            for patched in (False, True):\n                tls.requests.clear(); tls.counts.clear()\n                with self.subTest(authenticator_only=patched), patch.object(executor, 'stage_selected') as stage:\n                    session = executor.PublisherSession(root, selection, 'fixture-token', temporary_parent=root)\n                    with patch.object(wire, '_authenticate', side_effect=gates if patched else wire._authenticate):\n                        with self.assertRaises(wire.WireFailure) as failure:\n                            session.run_until_pause()\n                    self.assertEqual((failure.exception.code, failure.exception.effect), ('fence_blocked', 'none'))\n                    self.assertEqual(session.outcome, 'blocked_no_effect')\n                    self.assertIsNone(session.transition)\n                    stage.assert_not_called()\n                    self.assertEqual([r[1] for r in tls.requests], [] if patched else tls.expected_paths)\n                    self.assertTrue(all(r[0] == 'GET' and r[3] == b'' for r in tls.requests))\n                    self.assertEqual(self.mutations(tls), [])\n                    session.close()\n            with self.assertRaises(TypeError):\n", b"\n    def test_live_entry_is_blocked_without_real_verifiers_and_tag_guarantee(self):\n        with HTTPSFixture() as tls, tempfile.TemporaryDirectory() as root:\n            selection = Selection(tls.subject, 41, 1, '1' * 64)\n            for patched in (False, True):\n                with self.subTest(authenticator_only=patched), patch.object(wire, '_connect') as connect:\n                    session = executor.PublisherSession(root, selection, 'fixture-token', temporary_parent=root)\n                    with patch.object(wire, '_authenticate', side_effect=gates if patched else wire._authenticate):\n                        with self.assertRaises(wire.WireFailure) as failure:\n                            session.run_until_pause()\n                    self.assertEqual(failure.exception.effect, 'none')\n                    self.assertEqual(session.outcome, 'blocked_no_effect')\n                    self.assertIsNone(session.transition)\n                    connect.assert_not_called()\n                    session.close()\n            with self.assertRaises(TypeError):\n"),
    ),
}
# END SEALED SOURCE
DISPATCH = (
    b'    import rc_pretag_integration_admission_profile as integration\n'
    b'    selected = integration.select(ref, root, git, entries, historical, release, release_tree, documents)\n'
    b'    if selected is not None:\n'
    b'        return selected\n'
)
NEW_CASES = {
    'rc_publication_admission_cases.AdmissionCases': (
        'test_exact_seven_jobs_returns_blocked_partial_evidence',
        'test_gate_digest_canonical_order_and_binding',
        'test_frozen_source_tree_and_repository_identity_rejected',
        'test_workflow_path_id_blob_mode_and_tree_completeness_rejected',
        'test_event_ref_and_pr_merge_selection_rejected',
        'test_exact_run_attempt_and_selected_job_ids_rejected',
        'test_exact_seven_job_names_status_and_times_rejected',
        'test_newer_unsuccessful_run_never_falls_back',
        'test_paginated_newest_run_selection_has_exact_inventory',
        'test_pagination_counts_duplicates_truncation_and_cap_rejected',
        'test_run_attempt_and_current_snapshot_drift_rejected',
        'test_job_inventory_and_fields_drift_rejected',
        'test_workflow_ref_source_tree_reobserve_drift_rejected',
        'test_late_newer_run_blocks_frozen_selection',
        'test_metadata_denial_absence_redirect_and_nonjson_rejected',
        'test_metadata_parser_limits_and_duplicate_fields_rejected',
        'test_cancelled_before_connect_sends_no_request',
        'test_cancelled_during_reads_returns_no_partial_result',
        'test_one_absolute_deadline_covers_all_reads',
        'test_repeat_invocation_reobserves_without_cached_authority',
        'test_authenticate_real_reads_and_blocks_remaining_gates',
        'test_public_entry_authenticates_then_blocks_before_staging',
        'test_all_direct_mutation_sinks_authenticate_and_send_no_mutation',
        'test_caller_claims_and_reports_cannot_bypass_fixed_authentication',
    ),
    'rc_pretag_integration_admission_cases.IntegrationAdmissionCompositionCases': (
        'test_exact_b_identity_and_fresh_historical_validation',
        'test_ordered_d_i_j_and_exact_four_document_overlay',
        'test_wrong_repeated_nested_correction_and_same_tree_parents_reject',
        'test_all_paths_modes_pins_and_entry_counts_are_exact',
        'test_individual_and_total_budgets_fail_closed',
        'test_exact_dispatch_and_legacy_inverses_recover_complete_b_bytes',
        'test_missing_duplicate_outside_and_binary_inverse_edits_reject',
        'test_selected_historical_and_release_content_errors_are_terminal',
        'test_actual_candidate_validation_is_never_cached',
        'test_original1232_strict303_ids_and_legacy_assertions_are_preserved',
        'test_readonly_workflow_and_held_sources_remain_bounded',
        'test_new36_inventory_and_exceptional_outcomes_reject',
    ),
}
CLASS = 'rc_pretag_integration_admission_cases.IntegrationAdmissionCompositionCases'
NAMES = NEW_CASES[CLASS]
DIGEST = '5c11731e861ebc18ba34abe638b14cd48790edc15cbeda143a9535f8edb42bd9'


def normalize(path, current):
    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""
    assert type(path) is str and type(current) is bytes, 'integration inverse input'
    if path not in BASE_PINS:
        return current
    identity = o.pin(current)
    baseline = BASE_PINS[path]
    if identity == baseline[1:3] or identity in PRIOR_PINS.get(path, ()):
        return current
    row = SOURCE_PINS[path]
    assert (identity, len(current), len(current.splitlines())) == (row[1:3], row[3], row[4]), path
    restored = current
    for before, after in reversed(FRAGMENTS[path]):
        assert before and restored.count(before) == 1, 'integration fragment missing or duplicated'
        restored = restored.replace(before, after, 1)
    assert (o.pin(restored), len(restored), len(restored.splitlines())) == (
        baseline[1:3], baseline[3], baseline[4]), 'complete integration B inverse'
    return restored


def topology(ref, root, git, release):
    """Only D[B], I[B,D], J[R,I]; no correction chains or ancestry inference."""
    if release != p.R:
        raise o.TopologyError('integration_release_anchor')
    parents = o._parents(ref, root, git)
    if parents == [B]:
        kind, tip, source = 'nonrelease', ref, ref
    elif len(parents) == 2 and parents[0] == B:
        kind, tip, source = 'nonrelease', ref, parents[1]
    elif len(parents) == 2 and parents[0] == p.R:
        kind, tip = 'release', parents[1]
        feature_parents = o._parents(tip, root, git)
        if len(feature_parents) != 2 or feature_parents[0] != B:
            raise o.TopologyError('integration_feature_parents')
        source = feature_parents[1]
    else:
        raise o.TopologyError('integration_candidate_parents')
    if o._parents(source, root, git) != [B]:
        raise o.TopologyError('integration_candidate_parent')
    return kind, tip, source


def content(ref, root, git, entries, historical, release, release_tree, documents):
    """Fresh immutable B admission, exact candidate pins and complete reviewed delta."""
    assert (release, release_tree, documents) == (p.R, p.R_TREE, p.R_DOCUMENTS)
    assert tuple(o._parents(B, root, git)) == B_PARENTS, 'integration B parents'
    assert git('rev-parse', B + '^{tree}', root=root).decode().strip() == B_TREE, 'integration B tree'
    baseline = p.selected_profile(B, root, git, entries, historical, release, release_tree, documents)
    assert baseline == entries(B, root) and len(baseline) == 1745
    actual, paths = entries(ref, root), CAPS.keys()
    assert len(paths) == 26 and SOURCE_PINS.keys() == paths - {PROFILE}
    assert baseline.keys() & paths == BASE_PINS.keys() and len(BASE_PINS) == 19
    assert FRAGMENTS.keys() == BASE_PINS.keys() and PRIOR_PINS.keys() <= BASE_PINS.keys()
    assert actual.keys() == baseline.keys() | paths and len(actual) == 1752
    assert {path for path in actual if actual[path] != baseline.get(path)} == paths
    assert all(actual[path] == value for path, value in baseline.items() if path not in paths)
    assert all(actual[path][:2] == ('100644', 'blob') for path in paths)
    assert all(actual[path] == (row[0], 'blob', row[1]) for path, row in SOURCE_PINS.items())
    data = {path: git('cat-file', 'blob', actual[path][2], root=root) for path in paths}
    for path, (mode, blob, digest, size, count) in SOURCE_PINS.items():
        assert mode == '100644' and o.pin(data[path]) == (blob, digest), path
        assert (len(data[path]), len(data[path].splitlines())) == (size, count), path
    for path, row in BASE_PINS.items():
        assert baseline[path] == (row[0], 'blob', row[1]), path
        assert normalize(path, data[path]) == git('cat-file', 'blob', baseline[path][2], root=root), path
    p.authenticated._budgets(ref, B, root, git, data, CAPS, DELTA_LIMIT, 'integration_delta_budget')
    return actual


def select(ref, root, git, entries, historical, release, release_tree, documents):
    """Only topology mismatch delegates; selected and historical content errors escape."""
    ref = o._commit(ref, root, git)
    try:
        kind, tip, source = topology(ref, root, git, release)
    except o.TopologyError:
        return None
    expected = content(source, root, git, entries, historical, release, release_tree, documents)
    assert entries(tip, root) == expected
    if kind == 'release':
        return o.release_content(ref, expected, root, git, entries, release, release_tree, documents)
    return expected
