"""Finite downloader source admission; independent complete-tree review binds this module."""
import rc_pretag_ownership_profile as o
import rc_pretag_publication_profile as p

M = '7de3244adc367fa60463d1e3b64c92f211d2fda8'
M_TREE = 'c499ee350af610c142652520c35da994215a6f70'
M_PARENTS = ('08bd1c79d3394321578444a2d2722c2bf9e8eb1d', 'd13ffd7dd6b90f5cfb73d78395a4944df92924c0')
PROFILE = 'scripts/rc_pretag_download_budget_profile.py'
CASES = 'scripts/rc_pretag_download_budget_cases.py'
DISPATCHER = 'scripts/rc_pretag_final_admission_profile.py'
WORKFLOW = '.github/workflows/issue88-publication-executor.yml'
TRANSPORT = 'scripts/rc_consumer_transport.py'
CAPS = {
    'scripts/rc_consumer_transport.py': (400, 200),
    'scripts/rc_consumer_proof_fixtures.py': (85, 40),
    'scripts/rc_pretag_ownership_tests.py': (385, 12),
    'scripts/rc_pretag_publication_adapters.py': (260, 8),
    'scripts/rc_pretag_final_admission_profile.py': (270, 6),
    'scripts/rc_pretag_final_admission_cases.py': (430, 55),
    '.github/workflows/issue88-publication-executor.yml': (120, 40),
    'scripts/rc_consumer_download_budget_cases.py': (480, 480),
    'scripts/rc_pretag_download_budget_profile.py': (400, 400),
    'scripts/rc_pretag_download_budget_cases.py': (400, 400),
    'docs/specs/issue88-download-budget/requirements.md': (40, 40),
    'docs/specs/issue88-download-budget/design.md': (70, 70),
    'docs/specs/issue88-download-budget/tasks.md': (60, 60),
}
BASE_PINS = {
    'scripts/rc_consumer_transport.py': ('100644', 'b1e93e5cf58b95275567003748ac36cdcb75d5d3', '2555906190830843de21c8e54d3fca3f2043bae3330a17109d72bdf7782ca703', 10946, 250),
    'scripts/rc_consumer_proof_fixtures.py': ('100644', 'ee7f3f7a70fcbe274665bcc71fe66c371ddaa89a', '11e678c770a7ca70fcfcfd8fb920671ac8dd396e716854d5139635830d33ff21', 2109, 53),
    'scripts/rc_pretag_ownership_tests.py': ('100644', '4bf8ddbe8b2b2ffc3c0bbea1a473cf0c26d6b56e', '8f40b75ada5a5ba0d6dd652aa015ed28a7fd1af22d2c603db3b0d40b420af0d5', 22767, 377),
    'scripts/rc_pretag_publication_adapters.py': ('100644', '9600a78904440a71e807af95a1d4cc20121a0dd6', 'a1f8734d53bba966709c1cfdaa4bad11ef37c4c8f42256141540741b17502042', 24882, 251),
    'scripts/rc_pretag_final_admission_profile.py': ('100644', '091798b87f797fac4554d534a1b47362db0d8602', 'b1b5102667957612b39db68c2a7ea8939007ff0f74940e71d786e6448503d23e', 47933, 255),
    'scripts/rc_pretag_final_admission_cases.py': ('100644', 'c169ac26b007550ba817095a0be4cd606ca7f992', 'af06d235bc76fb56293a0f2f11edd915737758c6e5f7decf210ea41890f7bc5a', 25308, 387),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'f3cf8b1e3f337204f423ae200e667aaf9d34e3f8', '5fedc956307b75e7d59c3f5aeda153b6e3e64dd618700141862149c3fda37d7a', 6617, 89),
}
PRIOR_PINS = {
    'scripts/rc_pretag_publication_adapters.py': (('a7b2fa2675551c0d6156192e57266d697cbbf544', '88b4a1452a9f4b050e1f7d7767eb202b07dab3d5bce17c275a60e3e0fd9ae329'), ('669f38760c6ea949b468d5c140a684570c009994', 'fbbea7fac1121f8b7f1aa7b1237c7633292b2e7921d15c53bc0f776913d1bad6'), ('5fe498145f77d1f73f8f1142810f2d1441ed0bcd', 'b5a822b35a105e5d7dd64997690ac9612dece7f900447aeb440d1eeb46586687')),
    '.github/workflows/issue88-publication-executor.yml': (('d06143c505bf739dfd4336ea97c20b5850d15128', 'ceb14dd7012995f1d3400e1eb7dfc24533b564cd9a039e2592c74b153d036634'), ('c6cc466d9d2520b668508e6fbd9754f1ac1cc7ef', '850aea3f1d81c00322f8c8ca1adf84a5abddb5c75d916066394f41a521397e4e')),
}
DELTA_LIMIT = 2000
# BEGIN SEALED SOURCE
SOURCE_PINS = {
    'scripts/rc_consumer_transport.py': ('100644', '476f7435e4c59c696261eec1f35868fe77dbb15a', '84e7167e881cf6b2b90071a9f85abd76154524358a8f4f3d8535294558d926e7', 14205, 330),
    'scripts/rc_consumer_proof_fixtures.py': ('100644', 'ee52d29c787ebaf1f523fa16320f75dde36354d3', '2356dad478b0ea91d344709ab02ae5d2b01e6ac27bce15c35c3fb8cf666d85bf', 2761, 67),
    'scripts/rc_pretag_ownership_tests.py': ('100644', 'e6ecfa8a7976215ea9d5fbc4eb3e8a60fdca62ee', '07711c5fa4b78855a98a16be87b8653dbff23620b36e5b76324e8faea2aa7711', 22900, 378),
    'scripts/rc_pretag_publication_adapters.py': ('100644', 'c9b72ae86c375d1c2b018ea66d0486b2945db0b8', 'c55a410f9e7098cae68d058f62c6c0f8588125ad4e07b23c99e4434635bc39e4', 24942, 252),
    'scripts/rc_pretag_final_admission_profile.py': ('100644', '91e8cd4d7f87a7b81863a6767cb0731838b0be5c', 'cceaf9dbdc7123e37f837be15afa5270213ec62bfb5172242f53fa928a5c6129', 48267, 261),
    'scripts/rc_pretag_final_admission_cases.py': ('100644', '9300e9d088d408d5e6634a173a7ff8860a2a2577', '2b3460fb7b655ded55558205dbb054364679beafb30b4d305e542f143fc34143', 25668, 388),
    '.github/workflows/issue88-publication-executor.yml': ('100644', 'a81e9404bae5e4a56599eb0455026c207acbdc27', 'ef64753deb51f2260812bf136ad4bca0d811bc84e61e601e80697fdef314181c', 7601, 99),
    'scripts/rc_consumer_download_budget_cases.py': ('100644', 'a60a1b5473d59ab98fd70202ff9049a2f998f819', '8891b4d12bbc110f980ee408dca1084a206d32648c4e55a891e89da68cfba728', 19736, 336),
    'scripts/rc_pretag_download_budget_cases.py': ('100644', 'd33ac1111e2d457e6a6aa9e595687f3217a1334f', '3f2b5a8528c3ce5d60e03889011f716b45906d3bd7a86f7d037f94a5e513c380', 28665, 400),
    'docs/specs/issue88-download-budget/requirements.md': ('100644', '47382bd9503e6f7c52a130ef1c3248a52439a494', '70beba0f4f1590f71a3e726a627865d6766a611660fae15d90010a502c35e160', 3008, 35),
    'docs/specs/issue88-download-budget/design.md': ('100644', '0a4c24fc050820f06bb411e357187db2bfce2300', '87b840fe17e81767a45a428b6e8c9a43f3c634a1e5e09a934e0da621ff158760', 4673, 46),
    'docs/specs/issue88-download-budget/tasks.md': ('100644', '50ba281d3d48878433f0d972fac3392984855dff', '670f1fd0f77d7e590dc287ef8d9da8c182f6ed79eb2f3be39a7a8f240aa76002', 3508, 47),
}
FRAGMENTS = {
    'scripts/rc_consumer_transport.py': (
        (b'from contextlib import ExitStack\nimport hashlib\nimport json\nimport math\nimport os\nfrom pathlib import Path\nimport re\n', b'from contextlib import ExitStack\nimport hashlib\nimport json\nimport os\nfrom pathlib import Path\nimport re\n'),
        (b"NoRedirect = wire.NoRedirect\nSAFE_ERRORS = wire.ERROR_CODES | frozenset({\n    'transport_deadline_exceeded', 'download_digest_mismatch',\n    'transport_cancelled', 'invalid_transport_deadline',\n    'unsafe_private_io', 'invalid_private_mode', 'unsafe_path', 'unsafe_absolute_path',\n    'private_root_closed', 'private_root_replaced', 'unsafe_private_directory',\n    'unsafe_private_file', 'unknown_private_directory', 'private_directory_replaced',\n", b"NoRedirect = wire.NoRedirect\nSAFE_ERRORS = wire.ERROR_CODES | frozenset({\n    'transport_deadline_exceeded', 'download_digest_mismatch',\n    'unsafe_private_io', 'invalid_private_mode', 'unsafe_path', 'unsafe_absolute_path',\n    'private_root_closed', 'private_root_replaced', 'unsafe_private_directory',\n    'unsafe_private_file', 'unknown_private_directory', 'private_directory_replaced',\n"),
        (b"\n\nclass _Download:\n    def __init__(self, deadline, clock, check_active=None, *, shared=False):\n        self.deadline, self.clock = deadline, clock\n        self.check_active, self.shared = check_active, shared or check_active is not None\n        self.process = None\n        self.uncertain = False\n        self.escalated = False\n        self.disposed = False\n\n    def check(self):\n        wait = remaining(self.deadline, self.clock)\n        if self.check_active is None:\n            return wait\n        code = None\n        try:\n            if self.check_active() is not None:\n                code = 'artifact_transport_failed'\n        except (KeyboardInterrupt, SystemExit):\n            raise\n        except BaseException as error:\n            code = 'artifact_transport_failed'\n            try:\n                value = error.code\n                if type(value) is str:\n                    code = {'cancelled': 'transport_cancelled',\n                            'timeout': 'transport_deadline_exceeded'}.get(value, code)\n            except BaseException:\n                pass\n        if code:\n            raise ConsumerError(code)\n        return min(0.05, remaining(self.deadline, self.clock))\n\n    def wait_for_exit(self):\n        if self.check_active is None:\n            try:\n                return self.process.wait(timeout=remaining(self.deadline, self.clock))\n            except subprocess.TimeoutExpired:\n                if self.shared:\n                    self.check()\n                raise\n        # Neither the operation budget nor this EOF phase budget can be renewed.\n        eof_deadline = min(self.deadline, self.clock() + READ_TIMEOUT)\n        while True:\n            wait = self.check()\n            now = self.clock()\n            need(now < self.deadline, 'transport_deadline_exceeded')\n            wait = min(wait, eof_deadline - now)\n            need(wait > 0, 'artifact_transport_failed')\n            try:\n                result = self.process.wait(timeout=wait)\n            except subprocess.TimeoutExpired:\n                continue\n            self.check()\n            now = self.clock()\n            need(now < self.deadline, 'transport_deadline_exceeded')\n            need(now < eof_deadline, 'artifact_transport_failed')\n            return result\n\n    def start(self, opener):\n        if opener is None:\n", b'\n\nclass _Download:\n    def __init__(self, deadline, clock):\n        self.deadline, self.clock = deadline, clock\n        self.process = None\n        self.uncertain = False\n        self.escalated = False\n        self.disposed = False\n\n    def start(self, opener):\n        if opener is None:\n'),
        (b'            # Library-only test seam. The CLI cannot supply a fixture launcher.\n            self.process = opener.start_worker()\n        # Take ownership immediately, even if descriptor setup subsequently fails.\n        self.check()\n        os.set_blocking(self.process.stdin.fileno(), False)\n        os.set_blocking(self.process.stdout.fileno(), False)\n        if self.shared:\n            self.check()\n\n    def exchange(self, raw, size, digest, destination):\n        process = self.process\n', b'            # Library-only test seam. The CLI cannot supply a fixture launcher.\n            self.process = opener.start_worker()\n        # Take ownership immediately, even if descriptor setup subsequently fails.\n        remaining(self.deadline, self.clock)\n        os.set_blocking(self.process.stdin.fileno(), False)\n        os.set_blocking(self.process.stdout.fileno(), False)\n\n    def exchange(self, raw, size, digest, destination):\n        process = self.process\n'),
        (b'            output = None\n            selector.register(process.stdout, selectors.EVENT_READ)\n            while not eof:\n                wait = self.check()\n                events = selector.select(wait)\n                self.check()\n                for key, _ in events:\n                    if self.shared:\n                        self.check()\n                    if key.fileobj is process.stdin:\n                        try:\n                            count = os.write(process.stdin.fileno(), outgoing[sent:])\n', b'            output = None\n            selector.register(process.stdout, selectors.EVENT_READ)\n            while not eof:\n                wait = remaining(self.deadline, self.clock)\n                events = selector.select(wait)\n                remaining(self.deadline, self.clock)\n                for key, _ in events:\n                    if key.fileobj is process.stdin:\n                        try:\n                            count = os.write(process.stdin.fileno(), outgoing[sent:])\n'),
        (b"                            break\n                        received.extend(block)\n                        while len(received) >= 4:\n                            if self.shared:\n                                self.check()\n                            length = struct.unpack('!I', received[:4])[0]\n                            need(0 < length <= wire.MAX_FRAME, 'invalid_transport_ipc')\n                            if len(received) < length + 4:\n", b"                            break\n                        received.extend(block)\n                        while len(received) >= 4:\n                            length = struct.unpack('!I', received[:4])[0]\n                            need(0 < length <= wire.MAX_FRAME, 'invalid_transport_ipc')\n                            if len(received) < length + 4:\n"),
        (b"                                    need(total <= size and total <= MAX_ZIP, 'download_size_mismatch')\n                                    hasher.update(chunk)\n                                    if output is None:\n                                        if self.shared:\n                                            self.check()\n                                        output = files.enter_context(destination.open('artifact.zip', 'xb'))\n                                    self.check()\n                                    need(output.write(chunk) == len(chunk), 'artifact_transport_failed')\n                                    self.check()\n                                elif frame == b'D':\n                                    done = True\n                                elif frame[:1] == b'E':\n", b"                                    need(total <= size and total <= MAX_ZIP, 'download_size_mismatch')\n                                    hasher.update(chunk)\n                                    if output is None:\n                                        output = files.enter_context(destination.open('artifact.zip', 'xb'))\n                                    remaining(self.deadline, self.clock)\n                                    need(output.write(chunk) == len(chunk), 'artifact_transport_failed')\n                                    remaining(self.deadline, self.clock)\n                                elif frame == b'D':\n                                    done = True\n                                elif frame[:1] == b'E':\n"),
        (b"            need(total == size, 'download_size_mismatch')\n            need('sha256:' + hasher.hexdigest() == digest, 'download_digest_mismatch')\n            # This wait is still inside the one operation deadline.\n            need(self.wait_for_exit() == 0,\n                 'artifact_transport_failed')\n            self.check()\n        # PrivateRoot.open flushes, fsyncs and closes on context exit.\n        self.check()\n\n    def cleanup(self):\n        if self.uncertain:\n", b"            need(total == size, 'download_size_mismatch')\n            need('sha256:' + hasher.hexdigest() == digest, 'download_digest_mismatch')\n            # This wait is still inside the one operation deadline.\n            need(process.wait(timeout=remaining(self.deadline, self.clock)) == 0,\n                 'artifact_transport_failed')\n            remaining(self.deadline, self.clock)\n        # PrivateRoot.open flushes, fsyncs and closes on context exit.\n        remaining(self.deadline, self.clock)\n\n    def cleanup(self):\n        if self.uncertain:\n"),
        (b'        return not failed\n\n\ndef download_artifact_zip(api, artifact, destination, *, opener=None, clock=time.monotonic,\n                          deadline=None, check_active=None):\n    """One supervised download; test-only opener launch adapters never bypass IPC.\n\n    Synchronous OS launch/file I/O cannot be interrupted; late completion fails.\n', b'        return not failed\n\n\ndef download_artifact_zip(api, artifact, destination, *, opener=None, clock=time.monotonic):\n    """One supervised download; test-only opener launch adapters never bypass IPC.\n\n    Synchronous OS launch/file I/O cannot be interrupted; late completion fails.\n'),
        (b"         'invalid_download_metadata')\n    need(type(api.token) is str and bool(api.token), 'missing_actions_read_token')\n    need(bool(TRUSTED_STORAGE_HOSTS), 'storage_transport_unverified')\n    need(deadline is None or type(deadline) is int or\n         (type(deadline) is float and math.isfinite(deadline)), 'invalid_transport_deadline')\n    need(check_active is None or callable(check_active), 'artifact_transport_failed')\n    started = clock()\n    if deadline is not None:\n        # Compare before arithmetic: arbitrarily large built-in integers are valid.\n        need(deadline > started, 'transport_deadline_exceeded')\n    effective = started + TOTAL_TIMEOUT if deadline is None else min(deadline, started + TOTAL_TIMEOUT)\n    owner = _Download(effective, clock, check_active, shared=deadline is not None)\n    code, cancellation = None, None\n    try:\n        need(len(api.token) <= wire.MAX_REQUEST, 'invalid_transport_ipc')\n        raw = json.dumps({'id': ident, 'size': size, 'token': api.token},\n                         ensure_ascii=True, separators=(',', ':')).encode('ascii')\n        need(len(raw) <= wire.MAX_REQUEST, 'invalid_transport_ipc')\n        if owner.shared:\n            owner.check()\n        owner.start(opener)\n        owner.exchange(raw, size, digest, destination)\n    except ConsumerError as error:\n", b"         'invalid_download_metadata')\n    need(type(api.token) is str and bool(api.token), 'missing_actions_read_token')\n    need(bool(TRUSTED_STORAGE_HOSTS), 'storage_transport_unverified')\n    owner = _Download(clock() + TOTAL_TIMEOUT, clock)\n    code, cancellation = None, None\n    try:\n        need(len(api.token) <= wire.MAX_REQUEST, 'invalid_transport_ipc')\n        raw = json.dumps({'id': ident, 'size': size, 'token': api.token},\n                         ensure_ascii=True, separators=(',', ':')).encode('ascii')\n        need(len(raw) <= wire.MAX_REQUEST, 'invalid_transport_ipc')\n        owner.start(opener)\n        owner.exchange(raw, size, digest, destination)\n    except ConsumerError as error:\n"),
        (b"        failure = ConsumerError('transport_cleanup_uncertain')\n        failure.original_error_code = code or ('transport_cancelled' if cancellation else 'artifact_transport_failed')\n        raise failure\n    if code is None and cancellation is None and not owner.escalated:\n        try:\n            owner.check()\n        except ConsumerError as error:\n            code = _safe_code(error)\n        except (KeyboardInterrupt, SystemExit) as error:\n            cancellation = type(error)\n        except BaseException:\n            code = 'artifact_transport_failed'\n    if cancellation is SystemExit:\n        raise SystemExit(1)  # Cancellation must not turn the CLI exit status into success.\n    if cancellation:\n", b"        failure = ConsumerError('transport_cleanup_uncertain')\n        failure.original_error_code = code or ('transport_cancelled' if cancellation else 'artifact_transport_failed')\n        raise failure\n    if cancellation is SystemExit:\n        raise SystemExit(1)  # Cancellation must not turn the CLI exit status into success.\n    if cancellation:\n"),
    ),
    'scripts/rc_consumer_proof_fixtures.py': (
        (b"    for name in NAMES:\n        path = Path(root) / 'scripts' / (FIXTURE if name == NAMES[0] else name + '.py')\n        size, digest = PINS[name]\n        sizes = {size}\n        if name == 'rc_consumer_transport':\n            from rc_pretag_download_budget_profile import SOURCE_PINS, normalize\n            sizes.add(SOURCE_PINS['scripts/rc_consumer_transport.py'][3])\n        info = path.lstat()\n        if not stat.S_ISREG(info.st_mode) or info.st_size not in sizes:\n            raise ValueError('historical_source_rejected')\n        with path.open('rb') as source:\n            data = source.read(info.st_size + 1)\n        if len(data) != info.st_size:\n            raise ValueError('historical_source_rejected')\n        if name == 'rc_consumer_transport':\n            rejected = False\n            try:\n                data = normalize('scripts/rc_consumer_transport.py', data)\n            except AssertionError:\n                rejected = True\n            if rejected:\n                raise ValueError('historical_source_rejected')\n        if len(data) != size or hashlib.sha256(data).hexdigest() != digest:\n            raise ValueError('historical_source_rejected')\n        buffers[name] = data\n", b"    for name in NAMES:\n        path = Path(root) / 'scripts' / (FIXTURE if name == NAMES[0] else name + '.py')\n        size, digest = PINS[name]\n        info = path.lstat()\n        if not stat.S_ISREG(info.st_mode) or info.st_size != size:\n            raise ValueError('historical_source_rejected')\n        with path.open('rb') as source:\n            data = source.read(size + 1)\n        if len(data) != size or hashlib.sha256(data).hexdigest() != digest:\n            raise ValueError('historical_source_rejected')\n        buffers[name] = data\n"),
    ),
    'scripts/rc_pretag_ownership_tests.py': (
        (b'import rc_pretag_collection_result as result\nimport rc_pretag_collect_fixtures as fixtures\nfrom rc_consumer_io_ownership_tests import load_current\nfrom rc_pretag_integration_admission_profile import normalize as integration_bytes\n\n\nclass OwnershipCompositionTests(unittest.TestCase):\n', b'import rc_pretag_collection_result as result\nimport rc_pretag_collect_fixtures as fixtures\nfrom rc_consumer_io_ownership_tests import load_current\n\n\nclass OwnershipCompositionTests(unittest.TestCase):\n'),
        (b"        frozen = c._entries(c.publication.N, self.repo)\n        for path in o.CAPS:\n            self.good[path] = frozen[path] if path in (o.CHECKS, c.publication.OWNERSHIP_TESTS) else (\n                '100644', 'blob', self.blob(integration_bytes(path, (c.ROOT / path).read_bytes())))\n        self.pure = self.commit([o.M], self.good)\n\n    def content(self, ref):\n", b"        frozen = c._entries(c.publication.N, self.repo)\n        for path in o.CAPS:\n            self.good[path] = frozen[path] if path in (o.CHECKS, c.publication.OWNERSHIP_TESTS) else (\n                '100644', 'blob', self.blob((c.ROOT / path).read_bytes()))\n        self.pure = self.commit([o.M], self.good)\n\n    def content(self, ref):\n"),
        (b'        self.assertEqual((len(c.ALLOWED), len(o.CAPS), len(c.ALLOWED | o.CAPS.keys())), (22, 13, 32))\n        with self.assertRaises(o.TopologyError): self.selected(o.M)\n        for path, pin in o.NEW_PINS.items():\n            data = integration_bytes(path, (c.ROOT / path).read_bytes())\n            if path == o.CHECKS: data = c.publication.timeout_inverse(path, data)\n            self.assertEqual(o.pin(data), pin)\n\n', b'        self.assertEqual((len(c.ALLOWED), len(o.CAPS), len(c.ALLOWED | o.CAPS.keys())), (22, 13, 32))\n        with self.assertRaises(o.TopologyError): self.selected(o.M)\n        for path, pin in o.NEW_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            if path == o.CHECKS: data = c.publication.timeout_inverse(path, data)\n            self.assertEqual(o.pin(data), pin)\n\n'),
    ),
    'scripts/rc_pretag_publication_adapters.py': (
        (b'\ndef inverse_ownership(current, frozen):\n    assert p.OWNERSHIP_PINS.keys() == {p.OWNERSHIP_TESTS} and (len(frozen), len(frozen.splitlines())) == (22471, 372)\n    current = integration_bytes(p.OWNERSHIP_TESTS, current)\n    return inverse_adapter(p.OWNERSHIP_TESTS, current, frozen)\n# END EXACT M PUBLICATION ADAPTERS\n\n', b'\ndef inverse_ownership(current, frozen):\n    assert p.OWNERSHIP_PINS.keys() == {p.OWNERSHIP_TESTS} and (len(frozen), len(frozen.splitlines())) == (22471, 372)\n    return inverse_adapter(p.OWNERSHIP_TESTS, current, frozen)\n# END EXACT M PUBLICATION ADAPTERS\n\n'),
    ),
    'scripts/rc_pretag_final_admission_profile.py': (
        (b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'final inverse input\'\n    from rc_pretag_download_budget_profile import normalize as download_bytes\n    current = download_bytes(path, current)\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n', b'def normalize(path, current):\n    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""\n    assert type(path) is str and type(current) is bytes, \'final inverse input\'\n    if path not in BASE_PINS:\n        return current\n    identity = o.pin(current)\n'),
        (b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    import rc_pretag_download_budget_profile as download\n    selected = download.select(ref, root, git, entries, historical, release, release_tree, documents)\n    if selected is not None:\n        return selected\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n', b'def select(ref, root, git, entries, historical, release, release_tree, documents):\n    """Only topology mismatch delegates; selected and historical content errors escape."""\n    ref = o._commit(ref, root, git)\n    try:\n        kind, tip, source = topology(ref, root, git, release)\n    except o.TopologyError:\n'),
    ),
    'scripts/rc_pretag_final_admission_cases.py': (
        (b'import rc_pretag_publisher_executor_cases as old_cases\nimport rc_pretag_integration_admission_cases as previous_cases\nimport rc_pretag_final_admission_profile as x\nfrom rc_pretag_download_budget_profile import normalize as download_bytes\n\n\ndef inventory():\n', b'import rc_pretag_publisher_executor_cases as old_cases\nimport rc_pretag_integration_admission_cases as previous_cases\nimport rc_pretag_final_admission_profile as x\n\n\ndef inventory():\n'),
        (b"\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob(download_bytes(path, (c.ROOT / path).read_bytes()))) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n", b"\n    def setUp(self):\n        self.original = c._entries(x.M, self.repo)\n        self.good = self.original | {path: ('100644', 'blob', self.blob((c.ROOT / path).read_bytes())) for path in x.CAPS}\n        self.pure = self.commit([x.M], self.good)\n        self.feature = self.commit([x.M, self.pure], self.good)\n        self.overlay = self.good | c.RELEASE_DOCS\n"),
        (b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1752, 1758, 15, 9))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (400, 400))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob(download_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes())))\n        for path, row in x.SOURCE_PINS.items():\n            data = download_bytes(path, (c.ROOT / path).read_bytes())\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n", b"        self.assertEqual((len(self.original), len(self.good), len(x.CAPS), len(x.BASE_PINS)), (1752, 1758, 15, 9))\n        self.assertEqual(x.SOURCE_PINS.keys(), x.CAPS.keys() - {x.PROFILE})\n        self.assertEqual(x.CAPS[x.PROFILE], (400, 400))\n        self.assertEqual(self.good[x.PROFILE][2], c._blob((c.ROOT / x.PROFILE).read_bytes()))\n        for path, row in x.SOURCE_PINS.items():\n            data = (c.ROOT / path).read_bytes()\n            self.assertEqual(row, ('100644', *o.pin(data), len(data), len(data.splitlines())))\n            for index, value in enumerate(('100755', '0' * 40, '0' * 64, row[3] + 1, row[4] + 1)):\n                changed = list(row)\n"),
        (b"\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (2000, 1945))\n        data = {path: download_bytes(path, (c.ROOT / path).read_bytes()) for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'final_delta_budget')\n        budgets()\n", b"\n    def test_individual_and_total_budgets_fail_closed(self):\n        self.assertEqual((x.DELTA_LIMIT, sum(cap[1] for cap in x.CAPS.values())), (2000, 1945))\n        data = {path: (c.ROOT / path).read_bytes() for path in x.CAPS}\n        def budgets(git=c._git):\n            return p.authenticated._budgets(self.pure, x.M, self.repo, git, data, x.CAPS, x.DELTA_LIMIT, 'final_delta_budget')\n        budgets()\n"),
        (b"        self.assertEqual((len(x.DISPATCH.splitlines()), len(x.NORMALIZE.splitlines())), (4, 2))\n        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        for path in x.BASE_PINS:\n            current, frozen = download_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = download_bytes(x.DISPATCHER, (c.ROOT / x.DISPATCHER).read_bytes())\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n", b"        self.assertEqual((len(x.DISPATCH.splitlines()), len(x.NORMALIZE.splitlines())), (4, 2))\n        self.assertEqual(x.FRAGMENTS.keys(), x.BASE_PINS.keys())\n        for path in x.BASE_PINS:\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            with patch('builtins.open', side_effect=AssertionError('IO forbidden')), patch('subprocess.check_output', side_effect=AssertionError('git forbidden')):\n                self.assertEqual(x.normalize(path, current), frozen, path)\n                self.assertEqual(x.normalize(path, frozen), frozen, path)\n        current = (c.ROOT / x.DISPATCHER).read_bytes()\n        self.assertEqual((current.count(x.DISPATCH), current.count(x.NORMALIZE)), (1, 1))\n        self.assertEqual(current.replace(x.DISPATCH, b'', 1).replace(x.NORMALIZE, b'', 1), self.frozen(x.DISPATCHER))\n        self.assertEqual(c._git('diff', '--numstat', x.M, self.pure, '--', x.DISPATCHER, root=self.repo),\n"),
        (b"\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = download_bytes(path, (c.ROOT / path).read_bytes())\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n", b"\n    def test_missing_duplicate_outside_and_binary_inverse_edits_reject(self):\n        for path, fragments in x.FRAGMENTS.items():\n            current = (c.ROOT / path).read_bytes()\n            altered = [current + b'# outside\\n', b'\\xff']\n            for before, _ in fragments:\n                self.assertEqual(current.count(before), 1)\n"),
        (b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse(download_bytes(x.PROFILE, (c.ROOT / x.PROFILE).read_bytes()).decode())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n\n    def test_original1268_strict303_ids_and_legacy_assertions_are_preserved(self):\n", b"            fresh.assert_called_once()\n        with patch.object(x, 'M_TREE', '0' * 40), patch.object(self, '_select', side_effect=AssertionError('fresh required')), self.assertRaisesRegex(AssertionError, 'fresh required'):\n            self.verified_baseline(x.M, *self.args)\n        runtime = ast.parse((c.ROOT / x.PROFILE).read_text())\n        self.assertFalse(any('cache' in (getattr(node, 'id', getattr(node, 'attr', getattr(node, 'name', ''))) or '') for node in ast.walk(runtime)))\n\n    def test_original1268_strict303_ids_and_legacy_assertions_are_preserved(self):\n"),
        (b"                return node.args[1] if isinstance(node.func, ast.Name) and node.func.id == 'final_bytes' else node\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = download_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            def methods(data):\n                found = {}\n", b"                return node.args[1] if isinstance(node.func, ast.Name) and node.func.id == 'final_bytes' else node\n        for module in {item.split('.', 1)[0] for item in original}:\n            path = 'scripts/' + module + '.py'\n            current, frozen = (c.ROOT / path).read_bytes(), self.frozen(path)\n            self.assertEqual(x.normalize(path, current), frozen, path)\n            def methods(data):\n                found = {}\n"),
        (b'        self.assertFalse(set(original) & set(inventory()))\n\n    def test_readonly_workflow_and_held_sources_remain_bounded(self):\n        text = download_bytes(x.WORKFLOW, (c.ROOT / x.WORKFLOW).read_bytes()).decode()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n', b'        self.assertFalse(set(original) & set(inventory()))\n\n    def test_readonly_workflow_and_held_sources_remain_bounded(self):\n        text = (c.ROOT / x.WORKFLOW).read_text()\n        for fragment in ("on:\\n  push:\\n    branches: [\'ci/issue88-publisher-executor-*\']", \'permissions:\\n  contents: read\',\n                "os: [ubuntu-22.04, ubuntu-24.04]", "python-version: \'3.12\'", \'fetch-depth: 0, persist-credentials: false\',\n                "sha == os.environ[\'GITHUB_SHA\']", \'parents == [profile.M]\', \'before = checked()\', \'checked() == before\',\n'),
        (b"        self.assertTrue(all(not (c.ROOT / path).exists() and not (c.ROOT / path).is_symlink() for path in held))\n        for path in ('scripts/rc_release_eligibility.py', 'scripts/rc_publication_contract.py', 'scripts/rc_publication_stage.py',\n                'scripts/rc_consumer_io.py', 'scripts/rc_artifact_consumer.py', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual(download_bytes(path, (c.ROOT / path).read_bytes()), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n\n    def test_new36_inventory_and_exceptional_outcomes_reject(self):\n", b"        self.assertTrue(all(not (c.ROOT / path).exists() and not (c.ROOT / path).is_symlink() for path in held))\n        for path in ('scripts/rc_release_eligibility.py', 'scripts/rc_publication_contract.py', 'scripts/rc_publication_stage.py',\n                'scripts/rc_consumer_io.py', 'scripts/rc_artifact_consumer.py', 'src-tauri/src/workspace_snapshots/filesystem.rs'):\n            self.assertEqual((c.ROOT / path).read_bytes(), self.frozen(path), path)\n        self.assertTrue(all(self.good[path] == value for path, value in self.original.items() if path not in x.CAPS))\n\n    def test_new36_inventory_and_exceptional_outcomes_reject(self):\n"),
    ),
    '.github/workflows/issue88-publication-executor.yml': (
        (b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen one hundred forty-four cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n", b"        with: {ref: '${{ github.sha }}', fetch-depth: 0, persist-credentials: false}\n      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065\n        with: {python-version: '3.12'}\n      - name: Admit exact source and execute the frozen one hundred twenty cases\n        shell: python\n        run: |\n          import hashlib, json, os, pathlib, platform, subprocess, sys, traceback, unittest\n"),
        (b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_download_budget_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              import rc_pretag_download_budget_cases as download_budget\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n", b"              sys.path.insert(0, 'scripts')\n              import rc_pretag_composition_tests as c\n              import rc_pretag_publisher_executor_cases as x\n              import rc_pretag_final_admission_profile as profile\n              import rc_pretag_integration_admission_cases as admission\n              import rc_pretag_final_admission_cases as final_admission\n              git = lambda *args: c._git(*args).decode().strip()\n              assert sys.version_info[:2] == (3, 12) and platform.python_implementation() == 'CPython'\n              assert git('rev-parse', '--is-shallow-repository') == 'false'\n"),
        (b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'final-admission-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert final_admission.execution_valid(loaded, result)\n              names = download_budget.inventory()\n              suite = unittest.defaultTestLoader.loadTestsFromNames(names)\n              loaded = [test.id() for test in c._flatten(suite)]\n              with (evidence / 'download-budget-cases.log').open('w', encoding='utf-8') as output:\n                  result = unittest.TextTestRunner(stream=output, verbosity=2, resultclass=c.InventoryResult).run(suite)\n              receipt = {'loaded_ids': loaded, 'executed_ids': result.executed_ids, 'tests_run': result.testsRun,\n                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'download-budget-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert download_budget.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n", b"                         'skipped': result.skipped, 'expected_failures': result.expectedFailures, 'unexpected_successes': result.unexpectedSuccesses, 'successful': result.wasSuccessful()}\n              (evidence / 'final-admission-inventory.json').write_text(json.dumps(receipt, indent=2) + '\\n', encoding='utf-8')\n              assert final_admission.execution_valid(loaded, result)\n              assert checked() == before and git('rev-parse', 'HEAD') == sha and git('rev-parse', 'HEAD^{tree}') == tree\n              (evidence / 'source-after.json').write_text(json.dumps(binding | {'source_unchanged': True}, indent=2) + '\\n', encoding='utf-8')\n          except BaseException:\n"),
    ),
}
# END SEALED SOURCE
DISPATCH = (
    b'    import rc_pretag_download_budget_profile as download\n'
    b'    selected = download.select(ref, root, git, entries, historical, release, release_tree, documents)\n'
    b'    if selected is not None:\n'
    b'        return selected\n'
)
NORMALIZE = (
    b'    from rc_pretag_download_budget_profile import normalize as download_bytes\n'
    b'    current = download_bytes(path, current)\n'
)
NEW_CASES = {
    'rc_consumer_download_budget_cases.DownloadBudgetCases': ('test_defaults_and_shared_deadline_success_and_clamp', 'test_invalid_expired_boundary_and_huge_deadlines', 'test_cancelled_or_invalid_activity_prevents_launch', 'test_callback_mapping_and_legacy_interrupt_sanitization', 'test_real_startup_partial_ipc_and_late_launch_deadlines', 'test_real_startup_dns_tls_cancellation', 'test_loopback_trickle_obeys_shared_deadline', 'test_loopback_trickle_cancellation_reaps_worker', 'test_pipe_backpressure_keeps_budget_and_cancellation', 'test_owned_file_open_write_fsync_close_checkpoints', 'test_child_exit_and_cleanup_cannot_return_late_success', 'test_cleanup_uncertainty_overrides_cancel_and_stays_sticky'),
    'rc_pretag_download_budget_cases.DownloadBudgetCompositionCases': ('test_exact_f_identity_and_fresh_historical_validation', 'test_ordered_d_i_j_and_exact_four_document_overlay', 'test_wrong_repeated_nested_correction_and_same_tree_parents_reject', 'test_all_paths_modes_pins_and_entry_counts_are_exact', 'test_individual_and_total_budgets_fail_closed', 'test_exact_dispatch_and_seven_inverses_recover_complete_f_bytes', 'test_missing_duplicate_outside_and_binary_inverse_edits_reject', 'test_selected_historical_and_release_content_errors_are_terminal', 'test_actual_candidate_validation_is_never_cached', 'test_original1304_strict303_consumer452_ids_and_bodies_are_preserved', 'test_historical_consumer_envelope_and_readonly_workflow_remain_bounded', 'test_new24_inventory_and_exceptional_outcomes_reject'),
}
CLASS = 'rc_pretag_download_budget_cases.DownloadBudgetCompositionCases'
NAMES = NEW_CASES[CLASS]
DIGEST = 'e0f978c8fdf0a62c067208a2e49977279c993e421805b5887ac9ef402a3b7252'


def normalize(path, current):
    """Reverse only sealed new bytes; historical passthrough is a finite pin list."""
    assert type(path) is str and type(current) is bytes, 'download inverse input'
    if path not in BASE_PINS:
        return current
    identity = o.pin(current)
    baseline = BASE_PINS[path]
    if identity == baseline[1:3] or identity in PRIOR_PINS.get(path, ()):
        return current
    row = SOURCE_PINS[path]
    assert (identity, len(current), len(current.splitlines())) == (row[1:3], row[3], row[4]), path
    restored = current
    for before, after in reversed(FRAGMENTS[path]):
        assert before and restored.count(before) == 1, 'download fragment missing or duplicated'
        restored = restored.replace(before, after, 1)
    assert (o.pin(restored), len(restored), len(restored.splitlines())) == (
        baseline[1:3], baseline[3], baseline[4]), 'complete download M inverse'
    return restored


def topology(ref, root, git, release):
    """Only D[M], I[M,D], J[R,I]; no correction chains or ancestry inference."""
    if release != p.R:
        raise o.TopologyError('download_release_anchor')
    parents = o._parents(ref, root, git)
    if parents == [M]:
        kind, tip, source = 'nonrelease', ref, ref
    elif len(parents) == 2 and parents[0] == M:
        kind, tip, source = 'nonrelease', ref, parents[1]
    elif len(parents) == 2 and parents[0] == p.R:
        kind, tip = 'release', parents[1]
        feature_parents = o._parents(tip, root, git)
        if len(feature_parents) != 2 or feature_parents[0] != M:
            raise o.TopologyError('download_feature_parents')
        source = feature_parents[1]
    else:
        raise o.TopologyError('download_candidate_parents')
    if o._parents(source, root, git) != [M]:
        raise o.TopologyError('download_candidate_parent')
    return kind, tip, source


def content(ref, root, git, entries, historical, release, release_tree, documents):
    """Fresh immutable M admission, exact candidate pins and complete reviewed delta."""
    assert (release, release_tree, documents) == (p.R, p.R_TREE, p.R_DOCUMENTS)
    assert tuple(o._parents(M, root, git)) == M_PARENTS, 'download M parents'
    assert git('rev-parse', M + '^{tree}', root=root).decode().strip() == M_TREE, 'download M tree'
    baseline = p.selected_profile(M, root, git, entries, historical, release, release_tree, documents)
    assert baseline == entries(M, root) and len(baseline) == 1758
    actual, paths = entries(ref, root), CAPS.keys()
    assert len(paths) == 13 and SOURCE_PINS.keys() == paths - {PROFILE}
    assert baseline.keys() & paths == BASE_PINS.keys() and len(BASE_PINS) == 7
    assert FRAGMENTS.keys() == BASE_PINS.keys() and PRIOR_PINS.keys() <= BASE_PINS.keys()
    assert actual.keys() == baseline.keys() | paths and len(actual) == 1764
    assert {path for path in actual if actual[path] != baseline.get(path)} == paths
    assert all(actual[path] == value for path, value in baseline.items() if path not in paths)
    assert all(actual[path][:2] == ('100644', 'blob') for path in paths)
    assert all(actual[path] == (row[0], 'blob', row[1]) for path, row in SOURCE_PINS.items())
    data = {path: git('cat-file', 'blob', actual[path][2], root=root) for path in paths}
    for path, (mode, blob, digest, size, count) in SOURCE_PINS.items():
        assert mode == '100644' and o.pin(data[path]) == (blob, digest), path
        assert (len(data[path]), len(data[path].splitlines())) == (size, count), path
    for path, row in BASE_PINS.items():
        assert baseline[path] == (row[0], 'blob', row[1]), path
        assert normalize(path, data[path]) == git('cat-file', 'blob', baseline[path][2], root=root), path
    p.authenticated._budgets(ref, M, root, git, data, CAPS, DELTA_LIMIT, 'download_delta_budget')
    return actual


def select(ref, root, git, entries, historical, release, release_tree, documents):
    """Only topology mismatch delegates; selected and historical content errors escape."""
    ref = o._commit(ref, root, git)
    try:
        kind, tip, source = topology(ref, root, git, release)
    except o.TopologyError:
        return None
    expected = content(source, root, git, entries, historical, release, release_tree, documents)
    assert entries(tip, root) == expected
    if kind == 'release':
        return o.release_content(ref, expected, root, git, entries, release, release_tree, documents)
    return expected
